/* Beta Art hub - twelve-language switcher. Values map by index into K. */
(function(){"use strict";
var L=[["en","English","ltr"],["no","Norsk","ltr"],["tr","Türkçe","ltr"],["es","Español","ltr"],["fr","Français","ltr"],["de","Deutsch","ltr"],["pt","Português","ltr"],["ru","Русский","ltr"],["ar","العربية","rtl"],["zh","中文","ltr"],["ja","日本語","ltr"],["hi","हिन्दी","ltr"]];
var K=["label", "h1", "lead", "p1.role", "p1.body", "p1.go", "p2.role", "p2.body", "p2.go", "p3.role", "p3.body", "p3.go", "foot.copy", "nav.legal", "nav.privacy", "nav.ai", "nav.licence", "lang.label", "mark.human", "mark.human.note"];
var V={
"en":["Three properties · one archive", "Made by a human. Verified at the source.", "Three separate concepts, each with its own design language, built as static HTML, CSS and JavaScript — no build step, no framework, no external dependency beyond the brand's three typefaces.", "Project 01 · Public archive", "Twelve launch plates with accession labels, the three verification tests, a 35-category directory and licence tiers from kr 190. Museum paper, blind emboss, hairline rules.", "Enter the archive →", "Project 02 · Rights desk", "The digital studio: websites, branding, content, SEO and AI automation for people and companies, with a smart service finder, four packages and a browser-only AI Studio.", "Open the desk →", "Project 03 · Journal", "How the archive gets built: provenance, the three tests, shot planning, light this far north. Newsprint masthead, numbered entries, long-form reading with a dark mode.", "Open the journal →", "© 2026 Beta Art — Betül Öner. All rights reserved worldwide. The Beta Art name, mark, concept, page design and every photographic work are protected. Development preview — placeholder imagery, draft pricing, no backend connected.", "Legal notice", "Privacy (worldwide)", "AI & training data", "Licence terms", "Language", "Human approved", "Nothing is published here until a person has seen it and approved it."],
"no":["Tre nettsteder · ett arkiv", "Laget av et menneske. Verifisert ved kilden.", "Tre separate konsepter, hvert med sitt eget designspråk, bygget som statisk HTML, CSS og JavaScript — ingen byggeprosess, ingen rammeverk, ingen ekstern avhengighet utover merkevarens tre skrifttyper.", "Prosjekt 01 · Offentlig arkiv", "Tolv lanseringsplater med aksesjonsetiketter, de tre verifiseringstestene, en katalog med 35 kategorier og lisensnivåer fra kr 190. Museumspapir, blindpreg, hårfine linjer.", "Gå inn i arkivet →", "Prosjekt 02 · Rettighetskontor", "Det digitale studioet: nettsider, merkevare, innhold, SEO og AI-automatisering for privatpersoner og bedrifter, med smart tjenestefinner, fire pakker og et AI-studio som kjører kun i nettleseren.", "Åpne kontoret →", "Prosjekt 03 · Tidsskrift", "Slik bygges arkivet: proveniens, de tre testene, opptaksplanlegging, lyset så langt nord. Avistittel, nummererte innlegg, lang lesning med mørk modus.", "Åpne tidsskriftet →", "© 2026 Beta Art — Betül Öner. Alle rettigheter reservert i hele verden. Navnet Beta Art, merket, konseptet, sidedesignet og hvert fotografisk verk er beskyttet. Utviklingsversjon — plassholderbilder, foreløpige priser, ingen backend tilkoblet.", "Juridisk informasjon", "Personvern (hele verden)", "AI og treningsdata", "Lisensvilkår", "Språk", "Godkjent av menneske", "Ingenting publiseres her før et menneske har sett på det og godkjent det."],
"tr":["Üç mülk · tek arşiv", "Bir insan yaptı. Kaynağında doğrulandı.", "Her biri kendi tasarım diline sahip üç ayrı konsept; statik HTML, CSS ve JavaScript ile kuruldu — derleme adımı yok, çatı yok, markanın üç yazı tipi dışında dış bağımlılık yok.", "Proje 01 · Kamuya açık arşiv", "Kabul etiketleriyle on iki açılış plakası, üç doğrulama testi, 35 kategorilik dizin ve 190 kr'dan başlayan lisans kademeleri. Müze kâğıdı, kabartma, kılcal çizgiler.", "Arşive gir →", "Proje 02 · Haklar masası", "Dijital stüdyo: kişiler ve şirketler için web siteleri, marka, içerik, SEO ve yapay zekâ otomasyonu; akıllı hizmet bulucu, dört paket ve yalnızca tarayıcıda çalışan bir AI Stüdyo.", "Masayı aç →", "Proje 03 · Dergi", "Arşiv nasıl kuruluyor: köken, üç test, çekim planlaması, bu kadar kuzeyde ışık. Gazete başlığı, numaralı yazılar, karanlık modlu uzun okuma.", "Dergiyi aç →", "© 2026 Beta Art — Betül Öner. Dünya genelinde tüm hakları saklıdır. Beta Art adı, markası, konsepti, sayfa tasarımı ve her fotoğraf eseri korunmaktadır. Geliştirme önizlemesi — yer tutucu görseller, taslak fiyatlar, bağlı arka uç yok.", "Yasal bildirim", "Gizlilik (dünya geneli)", "Yapay zekâ ve eğitim verisi", "Lisans koşulları", "Dil", "İnsan onaylı", "Burada hiçbir şey, bir insan görüp onaylamadan yayımlanmaz."],
"es":["Tres sitios · un archivo", "Hecho por una persona. Verificado en el origen.", "Tres conceptos independientes, cada uno con su propio lenguaje de diseño, construidos como HTML, CSS y JavaScript estáticos: sin proceso de compilación, sin framework y sin más dependencia externa que las tres tipografías de la marca.", "Proyecto 01 · Archivo público", "Doce láminas de lanzamiento con etiquetas de registro, las tres pruebas de verificación, un directorio de 35 categorías y niveles de licencia desde 190 kr. Papel de museo, gofrado en seco, filetes finísimos.", "Entrar en el archivo →", "Proyecto 02 · Mesa de derechos", "El estudio digital: webs, marca, contenido, SEO y automatización con IA para personas y empresas, con buscador inteligente de servicios, cuatro paquetes y un estudio de IA que funciona solo en el navegador.", "Abrir la mesa →", "Proyecto 03 · Revista", "Cómo se construye el archivo: procedencia, las tres pruebas, planificación de tomas y la luz tan al norte. Cabecera de periódico, entradas numeradas y lectura larga con modo oscuro.", "Abrir la revista →", "© 2026 Beta Art — Betül Öner. Todos los derechos reservados en todo el mundo. El nombre Beta Art, su marca, su concepto, el diseño de las páginas y cada obra fotográfica están protegidos. Vista previa de desarrollo: imágenes provisionales, precios en borrador, sin backend conectado.", "Aviso legal", "Privacidad (mundial)", "IA y datos de entrenamiento", "Términos de licencia", "Idioma", "Aprobado por una persona", "Aquí no se publica nada hasta que una persona lo ha visto y lo ha aprobado."],
"fr":["Trois sites · une archive", "Fait par un être humain. Vérifié à la source.", "Trois concepts distincts, chacun avec son propre langage visuel, construits en HTML, CSS et JavaScript statiques — sans étape de build, sans framework, sans autre dépendance externe que les trois polices de la marque.", "Projet 01 · Archive publique", "Douze planches de lancement avec étiquettes d'inventaire, les trois tests de vérification, un répertoire de 35 catégories et des licences à partir de 190 kr. Papier de musée, gaufrage à sec, filets très fins.", "Entrer dans l'archive →", "Projet 02 · Bureau des droits", "Le studio numérique : sites web, image de marque, contenu, SEO et automatisation par IA pour particuliers et entreprises, avec recherche intelligente de service, quatre forfaits et un studio IA qui tourne uniquement dans le navigateur.", "Ouvrir le bureau →", "Projet 03 · Revue", "Comment l'archive se construit : provenance, les trois tests, préparation des prises de vue, la lumière si loin au nord. Manchette de journal, articles numérotés, lecture longue avec mode sombre.", "Ouvrir la revue →", "© 2026 Beta Art — Betül Öner. Tous droits réservés dans le monde entier. Le nom Beta Art, sa marque, son concept, le design des pages et chaque œuvre photographique sont protégés. Aperçu de développement : images provisoires, tarifs indicatifs, aucun backend connecté.", "Mentions légales", "Confidentialité (monde entier)", "IA et données d'entraînement", "Conditions de licence", "Langue", "Validé par un humain", "Rien n'est publié ici avant qu'un humain l'ait vu et approuvé."],
"de":["Drei Websites · ein Archiv", "Von einem Menschen gemacht. An der Quelle verifiziert.", "Drei eigenständige Konzepte, jedes mit eigener Gestaltungssprache, gebaut als statisches HTML, CSS und JavaScript — ohne Build-Schritt, ohne Framework, ohne externe Abhängigkeit außer den drei Hausschriften.", "Projekt 01 · Öffentliches Archiv", "Zwölf Startplatten mit Inventaretiketten, die drei Verifizierungstests, ein Verzeichnis mit 35 Kategorien und Lizenzstufen ab 190 kr. Museumspapier, Blindprägung, haarfeine Linien.", "Ins Archiv →", "Projekt 02 · Rechtestelle", "Das Digitalstudio: Websites, Markenauftritt, Inhalte, SEO und KI-Automatisierung für Privatpersonen und Unternehmen, mit intelligenter Servicesuche, vier Paketen und einem KI-Studio, das ausschließlich im Browser läuft.", "Zur Rechtestelle →", "Projekt 03 · Journal", "Wie das Archiv entsteht: Provenienz, die drei Tests, Aufnahmeplanung, das Licht so weit im Norden. Zeitungskopf, nummerierte Beiträge, Langtexte mit Dunkelmodus.", "Zum Journal →", "© 2026 Beta Art — Betül Öner. Alle Rechte weltweit vorbehalten. Der Name Beta Art, das Zeichen, das Konzept, das Seitendesign und jedes fotografische Werk sind geschützt. Entwicklungsvorschau — Platzhalterbilder, vorläufige Preise, kein Backend angebunden.", "Rechtliche Hinweise", "Datenschutz (weltweit)", "KI und Trainingsdaten", "Lizenzbedingungen", "Sprache", "Von einem Menschen geprüft", "Hier wird nichts veröffentlicht, bevor ein Mensch es gesehen und freigegeben hat."],
"pt":["Três sites · um arquivo", "Feito por uma pessoa. Verificado na origem.", "Três conceitos distintos, cada um com a sua própria linguagem de design, construídos em HTML, CSS e JavaScript estáticos — sem passo de compilação, sem framework e sem dependência externa além das três tipografias da marca.", "Projeto 01 · Arquivo público", "Doze pranchas de lançamento com etiquetas de registo, os três testes de verificação, um diretório de 35 categorias e níveis de licença a partir de 190 kr. Papel de museu, gravação a seco, filetes finíssimos.", "Entrar no arquivo →", "Projeto 02 · Mesa de direitos", "O estúdio digital: sites, marca, conteúdo, SEO e automação com IA para pessoas e empresas, com localizador inteligente de serviços, quatro pacotes e um estúdio de IA que corre apenas no navegador.", "Abrir a mesa →", "Projeto 03 · Revista", "Como o arquivo é construído: proveniência, os três testes, planeamento de captações e a luz tão a norte. Cabeçalho de jornal, entradas numeradas e leitura longa com modo escuro.", "Abrir a revista →", "© 2026 Beta Art — Betül Öner. Todos os direitos reservados em todo o mundo. O nome Beta Art, a sua marca, o conceito, o design das páginas e cada obra fotográfica estão protegidos. Pré-visualização de desenvolvimento — imagens provisórias, preços por confirmar, sem backend ligado.", "Aviso legal", "Privacidade (mundial)", "IA e dados de treino", "Termos de licença", "Idioma", "Aprovado por uma pessoa", "Nada é publicado aqui antes de uma pessoa ver e aprovar."],
"ru":["Три сайта · один архив", "Сделано человеком. Проверено у источника.", "Три отдельных концепции, у каждой свой визуальный язык, собранные на статичных HTML, CSS и JavaScript — без сборки, без фреймворка, без внешних зависимостей, кроме трёх фирменных шрифтов.", "Проект 01 · Открытый архив", "Двенадцать стартовых работ с инвентарными подписями, три теста проверки, каталог из 35 категорий и уровни лицензий от 190 kr. Музейная бумага, блинтовое тиснение, тончайшие линейки.", "Войти в архив →", "Проект 02 · Отдел прав", "Цифровая студия: сайты, бренд, контент, SEO и автоматизация с ИИ для людей и компаний, с умным подбором услуги, четырьмя пакетами и AI-студией, работающей только в браузере.", "Открыть отдел →", "Проект 03 · Журнал", "Как строится архив: происхождение, три теста, планирование съёмок, свет так далеко на севере. Газетный заголовок, нумерованные записи, длинное чтение с тёмной темой.", "Открыть журнал →", "© 2026 Beta Art — Betül Öner. Все права защищены во всём мире. Название Beta Art, знак, концепция, дизайн страниц и каждое фотографическое произведение охраняются. Предварительная версия — временные изображения, черновые цены, серверная часть не подключена.", "Правовая информация", "Конфиденциальность (весь мир)", "ИИ и данные для обучения", "Условия лицензии", "Язык", "Одобрено человеком", "Здесь ничего не публикуется, пока человек это не проверит и не одобрит."],
"ar":["ثلاثة مواقع · أرشيف واحد", "صنعه إنسان. موثّق من المصدر.", "ثلاثة مفاهيم منفصلة، لكل منها لغته التصميمية، مبنية بـ HTML وCSS وJavaScript ثابتة — بلا خطوة بناء، وبلا إطار عمل، وبلا اعتماد خارجي سوى خطوط العلامة الثلاثة.", "المشروع 01 · أرشيف عام", "اثنتا عشرة لوحة افتتاحية ببطاقات فهرسة، واختبارات التوثيق الثلاثة، ودليل من 35 فئة، ومستويات ترخيص تبدأ من 190 كرونة. ورق متحفي، وطبع بارز بلا حبر، وخطوط شعرية.", "ادخل الأرشيف ←", "المشروع 02 · مكتب الحقوق", "الاستوديو الرقمي: مواقع وهوية ومحتوى وتحسين محركات بحث وأتمتة بالذكاء الاصطناعي للأفراد والشركات، مع باحث خدمات ذكي وأربع باقات واستوديو ذكاء اصطناعي يعمل داخل المتصفح فقط.", "افتح المكتب ←", "المشروع 03 · مجلة", "كيف يُبنى الأرشيف: المصدر، والاختبارات الثلاثة، وتخطيط التصوير، والضوء في أقصى الشمال. ترويسة صحيفة، ومقالات مرقّمة، وقراءة طويلة بوضع داكن.", "افتح المجلة ←", "© 2026 Beta Art — Betül Öner. جميع الحقوق محفوظة في جميع أنحاء العالم. اسم بيتا آرت وعلامته ومفهومه وتصميم صفحاته وكل عمل تصويري محمية. نسخة تطويرية — صور مؤقتة، وأسعار أولية، ولا خادم متصل.", "إشعار قانوني", "الخصوصية (عالميًا)", "الذكاء الاصطناعي وبيانات التدريب", "شروط الترخيص", "اللغة", "باعتماد إنسان", "لا يُنشر هنا أي شيء قبل أن يراه إنسان ويوافق عليه."],
"zh":["三个站点 · 一座档案库", "由人类制作。在源头得到验证。", "三个彼此独立的概念，各有自己的设计语言，以静态 HTML、CSS 和 JavaScript 构建——没有构建步骤，没有框架，除品牌的三款字体外没有任何外部依赖。", "项目 01 · 公开档案库", "十二件首发作品，附有入藏标签、三项验证测试、35 个类别的目录，以及自 190 挪威克朗起的授权分级。博物馆纸、素压纹、发丝般的细线。", "进入档案库 →", "项目 02 · 版权事务台", "数字工作室：为个人与企业提供网站、品牌、内容、SEO 与 AI 自动化，配有智能服务导航、四种套餐，以及一个纯浏览器运行的 AI 工作室。", "进入事务台 →", "项目 03 · 杂志", "档案库是如何建成的：来源、三项测试、拍摄规划，以及北方高纬度的光线。报纸式报头、编号文章、带深色模式的长篇阅读。", "打开杂志 →", "© 2026 Beta Art — Betül Öner。保留全球所有权利。Beta Art 名称、标识、概念、页面设计及每一件摄影作品均受保护。开发预览——图片为占位素材，价格为草案，未连接后端。", "法律声明", "隐私（全球）", "AI 与训练数据", "授权条款", "语言", "真人审核通过", "这里的一切都要先经过真人查看并批准才会发布。"],
"ja":["三つのサイト · ひとつのアーカイブ", "人がつくりました。出どころで検証済み。", "それぞれ独自のデザイン言語をもつ三つの独立したコンセプト。静的な HTML、CSS、JavaScript で構築——ビルド工程なし、フレームワークなし、ブランドの三書体以外の外部依存なし。", "プロジェクト 01 · 公開アーカイブ", "受入ラベル付きの十二点の初期作品、三つの検証テスト、35カテゴリーの目録、そして 190 クローネからのライセンス区分。ミュージアム紙、空押し、髪の毛ほどの罫線。", "アーカイブへ →", "プロジェクト 02 · 権利窓口", "デジタルスタジオ：個人と企業のためのウェブサイト、ブランディング、コンテンツ、SEO、AI 自動化。スマート・サービス検索、四つのパッケージ、ブラウザ内だけで動く AI スタジオを備えています。", "窓口を開く →", "プロジェクト 03 · ジャーナル", "アーカイブがどう築かれるか：来歴、三つのテスト、撮影計画、これほど北の光。新聞風の題字、番号付きの記事、ダークモード付きの長文読書。", "ジャーナルを開く →", "© 2026 Beta Art — Betül Öner. 全世界における全ての権利を留保します。Beta Art の名称、マーク、コンセプト、ページデザイン、そしてすべての写真作品は保護されています。開発プレビュー——画像は仮素材、価格は草案、バックエンドは未接続です。", "法的通知", "プライバシー（全世界）", "AI と学習データ", "ライセンス条件", "言語", "人間が承認", "ここでは、人間が確認して承認するまで、何も公開されません。"],
"hi":["तीन साइटें · एक संग्रह", "एक इंसान ने बनाया। स्रोत पर सत्यापित।", "तीन अलग-अलग संकल्पनाएँ, हर एक की अपनी डिज़ाइन भाषा, स्थिर HTML, CSS और JavaScript से बनी — कोई बिल्ड चरण नहीं, कोई फ़्रेमवर्क नहीं, ब्रांड के तीन टाइपफ़ेस के अलावा कोई बाहरी निर्भरता नहीं।", "परियोजना 01 · सार्वजनिक संग्रह", "परिग्रहण लेबल के साथ बारह आरंभिक कृतियाँ, तीन सत्यापन परीक्षण, 35 श्रेणियों की निर्देशिका, और 190 क्रोनर से शुरू होने वाले लाइसेंस स्तर। म्यूज़ियम काग़ज़, बिना स्याही की उभरी छाप, बाल जैसी बारीक रेखाएँ।", "संग्रह में जाएँ →", "परियोजना 02 · अधिकार डेस्क", "डिजिटल स्टूडियो: व्यक्तियों और कंपनियों के लिए वेबसाइट, ब्रांडिंग, कंटेंट, SEO और AI ऑटोमेशन; स्मार्ट सेवा खोजक, चार पैकेज, और केवल ब्राउज़र में चलने वाला AI स्टूडियो।", "डेस्क खोलें →", "परियोजना 03 · पत्रिका", "संग्रह कैसे बनता है: उद्गम, तीन परीक्षण, शूट की योजना, और इतने उत्तर में मिलने वाला प्रकाश। अख़बारी शीर्षक, क्रमांकित प्रविष्टियाँ, डार्क मोड के साथ लंबी पठन-सामग्री।", "पत्रिका खोलें →", "© 2026 Beta Art — Betül Öner. विश्वभर में सर्वाधिकार सुरक्षित। Beta Art नाम, चिह्न, संकल्पना, पृष्ठ डिज़ाइन और प्रत्येक फ़ोटोग्राफ़िक कृति संरक्षित हैं। विकास पूर्वावलोकन — छवियाँ अस्थायी, मूल्य प्रारूप में, कोई बैकएंड जुड़ा नहीं।", "कानूनी सूचना", "गोपनीयता (विश्वभर)", "AI और प्रशिक्षण डेटा", "लाइसेंस शर्तें", "भाषा", "मनुष्य द्वारा अनुमोदित", "यहाँ कुछ भी तब तक प्रकाशित नहीं होता जब तक कोई व्यक्ति उसे देखकर अनुमोदित न कर दे।"]};
var STORE="beta-art-lang";
function dict(code){var r=V[code]||V.en,o={},i;for(i=0;i<K.length;i++)o[K[i]]=r[i];return o;}
function apply(code){
var meta=null,i;for(i=0;i<L.length;i++)if(L[i][0]===code)meta=L[i];
if(!meta){code="en";meta=L[0];}
var t=dict(code);
document.documentElement.lang=code;
document.documentElement.dir=meta[2];
document.querySelectorAll("[data-i18n]").forEach(function(el){
var v=t[el.getAttribute("data-i18n")];if(v!=null)el.textContent=v;});
try{localStorage.setItem(STORE,code);}catch(e){}
var sel=document.getElementById("lang-picker");
if(sel){if(sel.value!==code)sel.value=code;
if(t["lang.label"]){sel.setAttribute("aria-label",t["lang.label"]);
var lab=document.querySelector('label[for="lang-picker"]');if(lab)lab.textContent=t["lang.label"];}}}
function mount(){
var slot=document.getElementById("lang-slot");if(!slot||document.getElementById("lang-picker"))return;
var lab=document.createElement("label");lab.className="visually-hidden";lab.setAttribute("for","lang-picker");lab.textContent="Language";
var sel=document.createElement("select");sel.id="lang-picker";sel.className="lang-select";sel.setAttribute("aria-label","Language");
L.forEach(function(m){var o=document.createElement("option");o.value=m[0];o.textContent=m[1];sel.appendChild(o);});
sel.addEventListener("change",function(){apply(sel.value);});
slot.appendChild(lab);slot.appendChild(sel);}
function initial(){
var saved=null;try{saved=localStorage.getItem(STORE);}catch(e){}
if(saved)return saved;
var nav=(navigator.language||"en").slice(0,2).toLowerCase(),i;
for(i=0;i<L.length;i++)if(L[i][0]===nav)return nav;
return "en";}
function boot(){mount();apply(initial());}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
window.BetaArtI18n={apply:apply,languages:L};})();
