/* Field Notes - twelve-language switcher. Values map by index into K. */
(function(){"use strict";
var L=[["en","English","ltr"],["no","Norsk","ltr"],["tr","Türkçe","ltr"],["es","Español","ltr"],["fr","Français","ltr"],["de","Deutsch","ltr"],["pt","Português","ltr"],["ru","Русский","ltr"],["ar","العربية","rtl"],["zh","中文","ltr"],["ja","日本語","ltr"],["hi","हिन्दी","ltr"]];
var K=["nav.entries","nav.topics","nav.shotlist","nav.newsletter","nav.archive","nav.business","mast.strapline","lead.kicker","lead.standfirst","lead.readon","search.label","search.ph","topic.all","topic.provenance","topic.method","topic.light","topic.trade","topic.market","side.about","side.about.p1","side.about.p2","side.shotlist","side.buyers","side.mostread","side.plate","sub.title","sub.lead","sub.cta","sub.label","legal.copyright","lang.label"];
var V={
"en":["Entries","Topics","Shot list","Newsletter","The archive","Business","How a verified photography archive gets built","Essay · Provenance","For a century a photograph argued for itself. That arrangement has quietly ended — and the cost of proving otherwise falls on the people still going outside with a camera.","Read the essay →","Search entries","Search entries…","All","Provenance","Method","Light","Trade","Market","About this journal","Field Notes is written from inside the Beta Art archive: one photographer, one filing system, and a licensing desk that has to answer for every frame it sells.","Two or three entries a month. No sponsored posts, ever.","The launch shot list","Who buys the work","Most read","Plate of the month","Two letters a month","New entries, the next plates going onto the list, and a short note from the field. Unsubscribe in one click; the list is never passed on.","Subscribe","Your email address","© 2026 Beta Art — Betül Öner. All rights reserved worldwide. Every essay, photograph, catalogue record and page design on this site is a protected work. No text or image here may be used as AI training data.","Language"],
"no":["Innlegg","Emner","Opptaksliste","Nyhetsbrev","Arkivet","Bedrift","Slik bygges et verifisert fotoarkiv","Essay · Proveniens","I hundre år talte et fotografi for seg selv. Den ordningen er stille avsluttet — og kostnaden ved å bevise noe annet faller på dem som fortsatt går ut med et kamera.","Les essayet →","Søk i innlegg","Søk i innlegg…","Alle","Proveniens","Metode","Lys","Bransje","Marked","Om dette tidsskriftet","Field Notes skrives innenfra Beta Art-arkivet: én fotograf, ett arkivsystem, og et lisenskontor som må svare for hvert bilde det selger.","To eller tre innlegg i måneden. Aldri sponset innhold.","Opptakslisten for lanseringen","Hvem kjøper arbeidet","Mest lest","Månedens plate","To brev i måneden","Nye innlegg, de neste platene som settes på listen, og en kort hilsen fra felten. Meld deg av med ett klikk; listen deles aldri videre.","Abonner","E-postadressen din","© 2026 Beta Art — Betül Öner. Alle rettigheter reservert i hele verden. Hvert essay, fotografi, katalogpost og sidedesign på dette nettstedet er et beskyttet verk. Ingen tekst eller bilde her kan brukes som treningsdata for kunstig intelligens.","Språk"],
"tr":["Yazılar","Konular","Çekim listesi","Bülten","Arşiv","Kurumsal","Doğrulanmış bir fotoğraf arşivi nasıl kurulur","Deneme · Köken","Bir yüzyıl boyunca fotoğraf kendi kendini savundu. Bu düzen sessizce sona erdi — ve aksini kanıtlamanın bedeli, hâlâ kamerayla dışarı çıkanların sırtına kaldı.","Denemeyi oku →","Yazılarda ara","Yazılarda ara…","Tümü","Köken","Yöntem","Işık","Sektör","Pazar","Bu dergi hakkında","Field Notes, Beta Art arşivinin içinden yazılıyor: tek bir fotoğrafçı, tek bir arşivleme düzeni ve sattığı her kareyi savunmak zorunda olan bir lisans masası.","Ayda iki ya da üç yazı. Asla sponsorlu içerik yok.","Açılış çekim listesi","Bu işi kimler satın alıyor","En çok okunanlar","Ayın plakası","Ayda iki mektup","Yeni yazılar, listeye girecek sıradaki plakalar ve sahadan kısa bir not. Tek tıkla ayrılın; liste hiçbir zaman paylaşılmaz.","Abone ol","E-posta adresiniz","© 2026 Beta Art — Betül Öner. Dünya genelinde tüm hakları saklıdır. Bu sitedeki her deneme, fotoğraf, katalog kaydı ve sayfa tasarımı korunan bir eserdir. Buradaki hiçbir metin veya görsel yapay zekâ eğitim verisi olarak kullanılamaz.","Dil"],
"es":["Entradas","Temas","Lista de tomas","Boletín","El archivo","Empresas","Cómo se construye un archivo fotográfico verificado","Ensayo · Procedencia","Durante un siglo la fotografía se defendió sola. Ese acuerdo ha terminado en silencio, y el coste de demostrar lo contrario recae en quienes siguen saliendo con una cámara.","Leer el ensayo →","Buscar entradas","Buscar entradas…","Todas","Procedencia","Método","Luz","Oficio","Mercado","Sobre esta revista","Field Notes se escribe desde dentro del archivo de Beta Art: un fotógrafo, un sistema de archivo y una mesa de licencias que debe responder por cada imagen que vende.","Dos o tres entradas al mes. Nunca contenido patrocinado.","La lista de tomas de lanzamiento","Quién compra este trabajo","Lo más leído","Lámina del mes","Dos cartas al mes","Nuevas entradas, las próximas láminas que entran en la lista y una nota breve desde el terreno. Cancela con un clic; la lista nunca se cede.","Suscribirse","Tu dirección de correo","© 2026 Beta Art — Betül Öner. Todos los derechos reservados en todo el mundo. Cada ensayo, fotografía, ficha de catálogo y diseño de página de este sitio es una obra protegida. Ningún texto ni imagen puede usarse como datos de entrenamiento de IA.","Idioma"],
"fr":["Articles","Thèmes","Liste de prises","Newsletter","Les archives","Entreprises","Comment se construit une archive photographique vérifiée","Essai · Provenance","Pendant un siècle, la photographie plaidait sa propre cause. Cet arrangement a discrètement pris fin, et le coût de la preuve retombe sur ceux qui sortent encore avec un appareil.","Lire l'essai →","Rechercher dans les articles","Rechercher dans les articles…","Tous","Provenance","Méthode","Lumière","Métier","Marché","À propos de cette revue","Field Notes s'écrit depuis l'intérieur des archives Beta Art : un photographe, un système de classement, et un bureau des licences qui doit répondre de chaque image vendue.","Deux ou trois articles par mois. Jamais de contenu sponsorisé.","La liste de prises de lancement","Qui achète ce travail","Les plus lus","Planche du mois","Deux lettres par mois","De nouveaux articles, les prochaines planches inscrites sur la liste et un mot bref depuis le terrain. Désabonnement en un clic ; la liste n'est jamais cédée.","S'abonner","Votre adresse e-mail","© 2026 Beta Art — Betül Öner. Tous droits réservés dans le monde entier. Chaque essai, photographie, fiche de catalogue et design de page de ce site est une œuvre protégée. Aucun texte ni aucune image ne peut servir de données d'entraînement pour une IA.","Langue"],
"de":["Beiträge","Themen","Aufnahmeliste","Newsletter","Das Archiv","Unternehmen","Wie ein verifiziertes Fotoarchiv entsteht","Essay · Provenienz","Ein Jahrhundert lang sprach die Fotografie für sich selbst. Diese Übereinkunft ist still zu Ende gegangen — und die Kosten des Gegenbeweises tragen jene, die noch mit der Kamera hinausgehen.","Essay lesen →","Beiträge durchsuchen","Beiträge durchsuchen…","Alle","Provenienz","Methode","Licht","Handwerk","Markt","Über dieses Journal","Field Notes entsteht aus dem Inneren des Beta-Art-Archivs: eine Fotografin, ein Ablagesystem und eine Lizenzstelle, die für jedes verkaufte Bild geradestehen muss.","Zwei oder drei Beiträge im Monat. Niemals gesponserte Inhalte.","Die Aufnahmeliste zum Start","Wer diese Arbeit kauft","Meistgelesen","Platte des Monats","Zwei Briefe im Monat","Neue Beiträge, die nächsten Platten auf der Liste und eine kurze Notiz aus dem Feld. Abmeldung mit einem Klick; die Liste wird nie weitergegeben.","Abonnieren","Ihre E-Mail-Adresse","© 2026 Beta Art — Betül Öner. Alle Rechte weltweit vorbehalten. Jedes Essay, jede Fotografie, jeder Katalogeintrag und das Seitendesign dieser Website sind geschützte Werke. Kein Text und kein Bild darf als KI-Trainingsdaten verwendet werden.","Sprache"],
"pt":["Entradas","Temas","Lista de captações","Newsletter","O arquivo","Empresas","Como se constrói um arquivo fotográfico verificado","Ensaio · Proveniência","Durante um século a fotografia defendeu-se sozinha. Esse acordo terminou em silêncio — e o custo de provar o contrário recai sobre quem ainda sai com uma câmara.","Ler o ensaio →","Pesquisar entradas","Pesquisar entradas…","Todas","Proveniência","Método","Luz","Ofício","Mercado","Sobre esta revista","Field Notes é escrito de dentro do arquivo da Beta Art: um fotógrafo, um sistema de arquivo e uma mesa de licenciamento que tem de responder por cada imagem que vende.","Duas ou três entradas por mês. Nunca conteúdo patrocinado.","A lista de captações de lançamento","Quem compra este trabalho","Mais lidos","Prancha do mês","Duas cartas por mês","Novas entradas, as próximas pranchas a entrar na lista e uma nota breve do terreno. Cancele com um clique; a lista nunca é cedida.","Subscrever","O seu endereço de email","© 2026 Beta Art — Betül Öner. Todos os direitos reservados em todo o mundo. Cada ensaio, fotografia, registo de catálogo e design de página deste site é uma obra protegida. Nenhum texto ou imagem pode ser usado como dados de treino de IA.","Idioma"],
"ru":["Записи","Темы","План съёмок","Рассылка","Архив","Бизнесу","Как строится проверенный фотоархив","Эссе · Происхождение","Целый век фотография говорила сама за себя. Этот порядок тихо закончился — и цену доказательства платят те, кто всё ещё выходит с камерой.","Читать эссе →","Поиск по записям","Поиск по записям…","Все","Происхождение","Метод","Свет","Ремесло","Рынок","Об этом журнале","Field Notes пишется изнутри архива Beta Art: один фотограф, одна система хранения и лицензионный отдел, который отвечает за каждый проданный кадр.","Две-три записи в месяц. Никакого спонсорского контента.","План съёмок к запуску","Кто покупает эту работу","Читают чаще всего","Работа месяца","Два письма в месяц","Новые записи, следующие работы, попадающие в список, и короткая заметка с места съёмки. Отписка в один клик; список никогда не передаётся третьим лицам.","Подписаться","Ваш адрес электронной почты","© 2026 Beta Art — Betül Öner. Все права защищены во всём мире. Каждое эссе, фотография, каталожная запись и дизайн страниц этого сайта являются охраняемыми произведениями. Никакой текст и никакое изображение отсюда не могут использоваться как данные для обучения ИИ.","Язык"],
"ar":["المقالات","الموضوعات","قائمة التصوير","النشرة البريدية","الأرشيف","للشركات","كيف يُبنى أرشيف تصوير موثّق","مقالة · المصدر","طوال قرن كانت الصورة تدافع عن نفسها. انتهى ذلك الترتيب بهدوء — وصار عبء الإثبات على من لا يزالون يخرجون بكاميرا.","اقرأ المقالة ←","ابحث في المقالات","ابحث في المقالات…","الكل","المصدر","المنهج","الضوء","المهنة","السوق","عن هذه المجلة","تُكتب Field Notes من داخل أرشيف بيتا آرت: مصوّرة واحدة، ونظام حفظ واحد، ومكتب ترخيص عليه أن يجيب عن كل صورة يبيعها.","مقالتان أو ثلاث شهريًا. ولا محتوى مموّل أبدًا.","قائمة تصوير الإطلاق","من يشتري هذا العمل","الأكثر قراءة","لوحة الشهر","رسالتان كل شهر","مقالات جديدة، واللوحات التالية التي تدخل القائمة، وملاحظة قصيرة من الميدان. إلغاء الاشتراك بنقرة واحدة؛ ولا تُمرَّر القائمة لأحد أبدًا.","اشترك","عنوان بريدك الإلكتروني","© 2026 Beta Art — Betül Öner. جميع الحقوق محفوظة في جميع أنحاء العالم. كل مقالة وصورة وسجل فهرسة وتصميم صفحة في هذا الموقع عمل محمي. ولا يجوز استخدام أي نص أو صورة هنا كبيانات لتدريب الذكاء الاصطناعي.","اللغة"],
"zh":["文章","主题","拍摄清单","订阅通讯","档案库","企业服务","一座经过验证的摄影档案库是如何建成的","随笔 · 来源","一个世纪以来，照片能为自己作证。这一默契已悄然终结——而举证的代价，落在了那些仍然背着相机出门的人身上。","阅读全文 →","搜索文章","搜索文章…","全部","来源","方法","光线","行业","市场","关于本刊","《Field Notes》写自 Beta Art 档案库内部：一位摄影师、一套归档系统，以及一个必须为售出的每一帧负责的授权部门。","每月两到三篇。永不接受赞助内容。","首发拍摄清单","谁在购买这些作品","阅读最多","本月作品","每月两封信","新文章、即将进入清单的下一批作品，以及一段来自现场的简短记录。一键退订；名单绝不外传。","订阅","你的电子邮箱","© 2026 Beta Art — Betül Öner。保留全球所有权利。本站的每一篇随笔、每一张照片、每一条编目记录及页面设计均为受保护作品。此处任何文字或图像均不得用作人工智能训练数据。","语言"],
"ja":["記事","トピック","撮影リスト","ニュースレター","アーカイブ","法人向け","検証済み写真アーカイブはこうしてつくられる","エッセイ · 来歴","一世紀のあいだ、写真はそれ自体が証拠でした。その前提は静かに終わり——証明の負担は、いまもカメラを持って外へ出る人の側に残されています。","エッセイを読む →","記事を検索","記事を検索…","すべて","来歴","方法","光","業界","市場","この雑誌について","Field Notes は Beta Art アーカイブの内側から書かれています。ひとりの写真家、ひとつの整理体系、そして売るすべての一枚に責任を負うライセンス窓口。","月に二、三本。スポンサー記事は一切ありません。","公開時の撮影リスト","この仕事を買うのは誰か","よく読まれている記事","今月の一枚","月に二通の手紙","新しい記事、次にリストへ加わる作品、そして現場からの短い便り。解除はワンクリック。名簿を外部に渡すことはありません。","購読する","メールアドレス","© 2026 Beta Art — Betül Öner. 全世界における全ての権利を留保します。本サイトのすべてのエッセイ、写真、目録記録およびページデザインは保護された著作物です。ここにあるいかなる文章も画像も、AI の学習データとして使用することはできません。","言語"],
"hi":["प्रविष्टियाँ","विषय","शूट सूची","न्यूज़लेटर","संग्रह","व्यवसाय","एक सत्यापित फ़ोटो संग्रह कैसे बनता है","निबंध · उद्गम","एक सदी तक तस्वीर अपनी गवाही खुद देती थी। वह व्यवस्था चुपचाप समाप्त हो गई — और अब प्रमाण जुटाने की लागत उन्हीं पर पड़ती है जो आज भी कैमरा लेकर बाहर निकलते हैं।","निबंध पढ़ें →","प्रविष्टियाँ खोजें","प्रविष्टियाँ खोजें…","सभी","उद्गम","विधि","प्रकाश","पेशा","बाज़ार","इस पत्रिका के बारे में","Field Notes बीटा आर्ट संग्रह के भीतर से लिखी जाती है: एक फ़ोटोग्राफ़र, एक फ़ाइलिंग व्यवस्था, और एक लाइसेंस डेस्क जिसे बेची गई हर तस्वीर का हिसाब देना होता है।","महीने में दो या तीन प्रविष्टियाँ। कभी कोई प्रायोजित सामग्री नहीं।","शुरुआती शूट सूची","यह काम कौन खरीदता है","सर्वाधिक पढ़े गए","महीने की कृति","महीने में दो पत्र","नई प्रविष्टियाँ, सूची में जुड़ने वाली अगली कृतियाँ, और मैदान से एक छोटा नोट। एक क्लिक में सदस्यता समाप्त करें; सूची कभी साझा नहीं की जाती।","सदस्यता लें","आपका ईमेल पता","© 2026 Beta Art — Betül Öner. विश्वभर में सर्वाधिकार सुरक्षित। इस साइट का प्रत्येक निबंध, फ़ोटोग्राफ़, सूची-अभिलेख और पृष्ठ डिज़ाइन एक संरक्षित कृति है। यहाँ का कोई भी पाठ या चित्र AI प्रशिक्षण डेटा के रूप में प्रयोग नहीं किया जा सकता।","भाषा"]};
var STORE="beta-art-lang";
function dict(code){var r=V[code]||V.en,o={},i;for(i=0;i<K.length;i++)o[K[i]]=r[i];return o;}
function apply(code){
var meta=null,i;for(i=0;i<L.length;i++)if(L[i][0]===code)meta=L[i];
if(!meta){code="en";meta=L[0];}
var t=dict(code);
document.documentElement.lang=code;
document.documentElement.dir=meta[2];
document.querySelectorAll("[data-i18n]").forEach(function(el){
var v=t[el.getAttribute("data-i18n")];if(v!=null)el.textContent=v;});
document.querySelectorAll("[data-i18n-attr]").forEach(function(el){
el.getAttribute("data-i18n-attr").split(",").forEach(function(pair){
var p=pair.split(":");if(p.length!==2)return;
var v=t[p[1].trim()];if(v!=null)el.setAttribute(p[0].trim(),v);});});
try{localStorage.setItem(STORE,code);}catch(e){}
var sel=document.getElementById("lang-picker");
if(sel){if(sel.value!==code)sel.value=code;
if(t["lang.label"]){sel.setAttribute("aria-label",t["lang.label"]);
var lab=document.querySelector('label[for="lang-picker"]');if(lab)lab.textContent=t["lang.label"];}}}
function mount(){
var slot=document.getElementById("lang-slot");if(!slot||document.getElementById("lang-picker"))return;
var lab=document.createElement("label");lab.className="visually-hidden";lab.setAttribute("for","lang-picker");lab.textContent="Language";
var sel=document.createElement("select");sel.id="lang-picker";sel.className="lang-select";sel.setAttribute("aria-label","Language");
L.forEach(function(m){var o=document.createElement("option");o.value=m[0];o.textContent=m[1];sel.appendChild(o);});
sel.addEventListener("change",function(){apply(sel.value);});
slot.appendChild(lab);slot.appendChild(sel);}
function initial(){
var saved=null;try{saved=localStorage.getItem(STORE);}catch(e){}
if(saved)return saved;
var nav=(navigator.language||"en").slice(0,2).toLowerCase(),i;
for(i=0;i<L.length;i++)if(L[i][0]===nav)return nav;
return "en";}
function boot(){mount();apply(initial());}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot);else boot();
window.BetaArtI18n={apply:apply,languages:L};})();
