# Norwegian service copy. Not a translation of the English — written in
# Norwegian, for a Norwegian buyer, with Norwegian references (NAV, Finn,
# Brønnøysund, MVA, EHF) where they belong. Keyed by slug.
NO = {}
def add(slug, **k): NO[slug] = k

# ---------------- PRIVAT ----------------
add("cv",
 title="CV og jobbsøknader",
 tag="Privat · Søknader",
 lead="En CV som kommer gjennom søkesystemet og fortsatt leses som om et menneske skrev den.",
 audience=["Folk som søker i Norge eller EØS og ikke får svar",
           "De som skifter bransje, der erfaringen ikke passer stillingstittelen",
           "Alle som har en CV som har vokst av seg selv i ti år"],
 problem="De fleste CV-er blir forkastet før et menneske ser dem. Søkesystemet leser filen, ser etter ordene fra utlysningen og rangerer det det finner. En pen tospaltet mal med stillingstitlene i sidefeltet får ofte null poeng — ikke fordi kandidaten er svak, men fordi filen ikke kunne leses.",
 solution="CV-en bygges opp på nytt i en struktur maskinen kan lese og et menneske vil lese: én spalte, ekte overskrifter, resultater før ansvarsområder, og ordene fra de utlysningene du faktisk svarer på. Du får hoveddokumentet og en kort guide for å tilpasse det per søknad.",
 process=[("Send det du har","Dagens CV, to utlysninger du ville søkt på, og det du er stolt av som mangler på siden."),
          ("Vi kartlegger","Erfaringen din mot det utlysningene faktisk screener for — hull blir navngitt, ikke pyntet over."),
          ("Bygger opp","Én spalte, resultater først, et tall i minst halvparten av linjene."),
          ("Tilpasningsguide","Hvilke tre linjer du endrer per søknad, og hvilke du aldri rører."),
          ("To runder","Én samlet tilbakemelding per runde.")],
 delivers=["Hoved-CV som .docx og PDF, filnavn fornavn-etternavn-cv.pdf",
           "Søknadsmal med de tre variable blokkene merket",
           "Én side tilpasningsguide",
           "Nøkkelordliste hentet fra reelle utlysninger i ditt fag"],
 extras=["LinkedIn-optimalisering — profilen rekrutterere faktisk søker i",
         "Intervjuforberedelse, to økter",
         "Norsk og engelsk versjon av samme CV"],
 faq=[("Dikter dere opp erfaring jeg ikke har?","Nei. Vi rammer inn det som er sant og navngir hullene, slik at du kan svare på dem i et intervju istedenfor å bli tatt på dem."),
      ("Trenger jeg bilde?","I Norge vanligvis ikke. Vi gir råd per marked og leverer begge versjoner hvis du vil ha valget.")])

add("linkedin",
 title="LinkedIn-optimalisering",
 tag="Privat · Profil",
 lead="Overskrift, om-tekst og erfaring skrevet om rundt det rekrutterere faktisk skriver i søkefeltet.",
 audience=["Folk som vil bli funnet framfor å søke",
           "Frilansere og konsulenter som selger fra profilen",
           "Alle som fortsatt har jobben de sluttet i for tre år siden øverst"],
 problem="LinkedIn er en søkemotor før det er et nettverk. Rekrutterere søker på ferdigheter og titler, og profilene som dukker opp er de som har de ordene i overskriften, om-teksten og rollebeskrivelsene. De fleste profiler har en stillingstittel og ingenting mer — så de dukker aldri opp.",
 solution="Profilen skrives om som et søkbart dokument: en overskrift som sier hva du gjør og for hvem, en om-tekst som åpner med resultatet du produserer, og erfaringsoppføringer som leses som bevis. Skrevet i din stemme, ikke i motivasjonsplakat-språk.",
 process=[("Gjennomgang","Hva du rangerer på i dag, og hva du burde rangere på."),
          ("Søkeord","De ti søkene du vil dukke opp i, hentet fra reelle utlysninger."),
          ("Omskriving","Overskrift, om-tekst, hver rolle, ferdigheter sortert etter hva som søkes på."),
          ("Oppsett","Åpen-for-jobb-innstillinger, fremhevet seksjon, hva du bør publisere først."),
          ("To runder","")],
 delivers=["Ny overskrift, om-tekst og hver erfaringsoppføring",
           "Prioritert ferdighetsliste",
           "Ti søkeord med begrunnelse",
           "En kort publiseringsplan for første måned"],
 extras=["CV bygget om til å matche profilen",
         "Personlig nettside som profilen peker til",
         "Redigering av banner og profilbilde"],
 faq=[("Publiserer dere for meg?","Nei, med mindre du kjøper tjenesten for sosialt innhold. Vi setter opp hva som skal sies; du beholder kontoen."),
      ("Norsk eller engelsk?","Begge, hvis markedet ditt er begge. Skrevet separat — en oversettelse leses som en oversettelse.")])

add("personal-site",
 title="Personlig nettside",
 tag="Privat · Web",
 lead="Én side som fungerer som adressen din på internett.",
 audience=["Frilansere som i dag sender folk til en sosial profil",
           "Jobbsøkere som trenger et sted å peke en QR-kode",
           "Alle som trenger en stabil lenke som overlever en plattform"],
 problem="En sosial profil er leid grunn. Plattformen bestemmer hvem som ser den, endrer utseendet og kan stenge kontoen. En egen side er den eneste adressen som blir din — men de fleste bygger den aldri, fordi verktøyene antar at du vil ha en tisiders brosjyre.",
 solution="Én side, bygget som statisk HTML, som svarer på tre spørsmål: hvem du er, hva du gjør, og hvordan folk får tak i deg. Rask, tilgjengelig, fungerer på telefon, og driftet et sted du kontrollerer. Ingen publiseringsløsning å vedlikeholde og ingen månedlig plattformavgift.",
 process=[("Brief","Seks spørsmål om hvem denne siden skal overbevise."),
          ("Struktur","Hva som ligger over folden, hva under, hva som kuttes."),
          ("Design og bygg","Mobil først, på merkevaren du har eller en vi setter."),
          ("Innhold","Skrevet for deg, med mindre du heller vil skrive selv."),
          ("Overlevering","Filer, drift satt opp, og en kort veiledning i å redigere.")],
 delivers=["Responsiv nettside på én side",
           "Kontaktskjema eller mailto, ditt valg",
           "Domene og drift satt opp",
           "Kildefiler og kort redigeringsguide",
           "Grunnleggende SEO: tittel, beskrivelse, strukturerte data"],
 extras=["Portefølje som en andre side",
         "Blogg satt opp på samme domene",
         "Flerspråklig versjon"],
 faq=[("Kan jeg redigere den selv etterpå?","Ja. Du får filene og en veiledning. Vil du ikke røre dem, gjør vi endringer per time."),
      ("Hva koster drift?","Ofte ingenting. Statiske sider driftes gratis hos flere leverandører; domenet koster rundt to hundre kroner i året.")])

add("portfolio",
 title="Portefølje",
 tag="Privat · Web",
 lead="Arbeidet ditt vist slik at noen kan vurdere det på tretti sekunder.",
 audience=["Designere, fotografer, utviklere og håndverkere",
           "Studenter og nyutdannede uten mange oppdrag ennå",
           "Alle som i dag sender en PDF på tjuefem megabyte"],
 problem="En portefølje som viser alt viser ingenting. Den som vurderer deg bruker under et minutt, og går forbi om de ikke raskt finner et arbeid som ligner det de trenger gjort. Kronologi hjelper deg; det hjelper ikke dem.",
 solution="Utvalg framfor volum. Seks til tolv arbeider, hvert med problemet, hva du gjorde og hva som kom ut av det — tre linjer, ikke tre avsnitt. Sortert etter hva du vil bli hyret for, ikke etter når det ble laget.",
 process=[("Utvalg","Hvilke arbeider som blir med, og hvorfor de andre ikke gjør det."),
          ("Rekkefølge","Det du vil bli hyret for, først."),
          ("Case-tekster","Problem, arbeid, resultat. Tre linjer hver."),
          ("Bygg","Rask, responsiv, bildene komprimert uten synlig tap."),
          ("Overlevering","Filer, drift og en mal for å legge til neste arbeid.")],
 delivers=["Portefølje med seks til tolv arbeider",
           "Case-tekst per arbeid",
           "Bilder optimalisert for web",
           "Mal for å legge til nye arbeider selv",
           "Kontaktvei som faktisk fungerer"],
 extras=["Personlig nettside som forsiden",
         "Redigering av arbeidsbildene",
         "CV som matcher porteføljen"],
 faq=[("Jeg har for få arbeider.","Da er tre gode nok. En kort portefølje med bevis slår en lang med fyllstoff."),
      ("Kan jeg vise arbeid gjort for en arbeidsgiver?","Sjekk avtalen din først. Vi hjelper med hvordan du beskriver det uten å bryte den.")])

add("social-content",
 title="Sosialt innhold",
 tag="Privat · Innhold",
 lead="En måned planlagt i én sitting, designet i én runde, publisert etter en plan.",
 audience=["Frilansere som selger fra en konto de ikke rekker å mate",
           "Folk som starter for seg selv og ikke vet hva de skal si",
           "Alle som publiserer i rykk og napp og deretter slutter"],
 problem="Det er ikke ideene som mangler. Det er at avgjørelsen om hva som skal publiseres tas hver dag, i tidsnød, og derfor ikke tas. Konsistens taper mot travelhet hver gang beslutningen er daglig.",
 solution="Beslutningen flyttes til én gang i måneden. Tolv innlegg planlagt, tekstet og designet på forhånd, med en publiseringsplan du kan følge på tre minutter om dagen. Ingen algoritmetriks — bare at det faktisk kommer noe.",
 process=[("Retning","Hvem du snakker til og hva du vil de skal huske."),
          ("Kalender","Tolv innlegg for måneden, tema per uke."),
          ("Tekst","Skrevet i din stemme, ikke i bransjespråk."),
          ("Design","Én visuell mal, gjenkjennelig på tvers av innleggene."),
          ("Overlevering","Filer, tekster og en enkel publiseringsplan.")],
 delivers=["Tolv innlegg med tekst og bilde per måned",
           "Innholdskalender med dato og tema",
           "Visuell mal du kan gjenbruke",
           "Månedlig kort gjennomgang av hva som fungerte"],
 extras=["Publisering og oppfølging som fast avtale",
         "Fotoredigering av eget materiale",
         "Personlig nettside som destinasjon"],
 faq=[("Publiserer dere for meg?","Som fast avtale, ja. Ellers får du filene og planen og gjør det selv på tre minutter om dagen."),
      ("Bruker dere AI til tekstene?","Til utkast og varianter, ja — og det står i det du får. Ferdig tekst leses og godkjennes av et menneske før den er din.")])

add("photo-editing",
 title="Fotoredigering",
 tag="Privat · Bilde",
 lead="Bildene dine ryddet, rettet og klargjort — uten at de slutter å se ut som deg.",
 audience=["Folk som trenger et profilbilde som holder",
           "Selgere av bruktting og bolig som taper på dårlige bilder",
           "Alle som har gode bilder tatt i dårlig lys"],
 problem="De fleste bilder feiler på tre ting: skjev horisont, feil hvitbalanse og for mye rot i kanten. Ingen av dem krever nytt utstyr. Alle tre avgjør om noen stoler på det de ser.",
 solution="Retting framfor forvandling. Eksponering, hvitbalanse, beskjæring og retusj som fjerner distraksjoner — ikke ansiktstrekk. Du får både den redigerte filen og originalen, alltid.",
 process=[("Gjennomgang","Hvilke bilder som er verdt arbeid, og hvilke som ikke er."),
          ("Retting","Horisont, eksponering, hvitbalanse, beskjæring."),
          ("Retusj","Distraksjoner fjernet. Ansiktet ditt beholdt."),
          ("Formater","Web, print og sosiale medier i riktige størrelser."),
          ("Overlevering","Redigert og original, filnavn du kan søke i.")],
 delivers=["Redigerte filer i full oppløsning",
           "Web-versjoner komprimert uten synlig tap",
           "Originalene urørt, alltid",
           "Filnavn som beskriver innholdet"],
 extras=["Bakgrunnsfjerning for produktbilder",
         "Sosialt innhold bygget på bildene",
         "Portefølje som viser dem fram"],
 faq=[("Endrer dere hvordan folk ser ut?","Nei. Vi fjerner distraksjoner, ikke trekk. Slankere, glattere eller yngre er ikke noe vi leverer."),
      ("Bruker dere generativ AI?","Ikke på innholdet i bildet. Vi kan fylle ut en kant teknisk, og da står det i leveransen.")])

add("career",
 title="Karriereveiledning",
 tag="Privat · Rådgivning",
 lead="To timer på å finne ut hva du faktisk søker på, før du søker på noe.",
 audience=["Folk som søker bredt og ikke får svar",
           "De som vurderer bransjeskifte og ikke vet hvor de står",
           "Alle som er i en jobb de vet de skal ut av"],
 problem="Å søke på alt er den dyreste strategien. Hver søknad koster to timer, ingen av dem er tilpasset, og avslagene sier ingenting om hvorfor. Uten en retning blir volum eneste plan, og volum uten retning gir avslag.",
 solution="Vi går gjennom hva du faktisk kan, hva markedet betaler for, og hvor de to overlapper. Resultatet er en kort liste med reelle stillingstyper, hva de krever, og hva du mangler for hver — skrevet ned, ikke sagt.",
 process=[("Forberedelse","Du sender CV, tre utlysninger som frister, og hva du ikke vil ha."),
          ("Samtale","To timer. Hva du kan, hva som betales for, hvor det møtes."),
          ("Kartlegging","Reelle stillingstyper med krav og gap per type."),
          ("Plan","Hva du gjør de neste tolv ukene, i rekkefølge."),
          ("Oppfølging","Én time etter fire uker.")],
 delivers=["Skriftlig kartlegging av tre til fem reelle stillingstyper",
           "Gapanalyse per type — hva du mangler og om det er verdt å skaffe",
           "Tolvukersplan med konkrete steg",
           "Én oppfølgingstime"],
 extras=["CV og søknader bygget mot kartleggingen",
         "LinkedIn-profil rettet mot de samme søkene",
         "Intervjuforberedelse"],
 faq=[("Skaffer dere meg jobb?","Nei. Vi hjelper deg å slutte å søke på det gale, og å søke bedre på det rette."),
      ("Er dette NAV-arbeid?","Nei, og det erstatter ikke NAV. Det er et betalt oppdrag som du eier resultatet av.")])

add("ai-assistant",
 title="Personlig AI-assistent",
 tag="Privat · AI",
 lead="Ett oppsett som tar den delen av uken du gjør om og om igjen.",
 audience=["Frilansere som skriver samme e-post tjue ganger i måneden",
           "Folk med mye administrasjon og lite tid",
           "Alle som vil bruke AI til noe konkret framfor å prøve alt"],
 problem="De fleste får ikke noe igjen for AI fordi de bruker den på alt, og derfor på ingenting skikkelig. Verktøyet er ikke problemet; mangelen på én valgt oppgave er.",
 solution="Vi finner oppgaven du gjør oftest og liker minst, og setter opp én assistent for nettopp den. Én oppgave, gjort godt, med instruksjonene skrevet ned slik at du kan endre dem selv.",
 process=[("Kartlegging","To uker av hva som faktisk spiser tiden din."),
          ("Valg","Én oppgave. Den du gjør mer enn fem ganger i uken."),
          ("Oppsett","Assistenten, instruksjonene, og grensene for hva den ikke skal gjøre."),
          ("Prøveuke","Du bruker den, vi retter svarene."),
          ("Overlevering","Instruksjonene skriftlig, så du kan endre dem selv.")],
 delivers=["Én assistent satt opp for én navngitt oppgave",
           "Instruksjonene skriftlig, i et format du kan redigere",
           "Liste over hva den ikke har lov til å gjøre",
           "En prøveuke med retting"],
 extras=["Flere oppgaver, én om gangen",
         "Personlig nettside eller portefølje",
         "Sosialt innhold som bruker samme oppsett"],
 faq=[("Trenger jeg et abonnement?","Ofte ett, og du eier det. Vi setter opp på verktøy du kan bytte fra."),
      ("Ser den mine private filer?","Bare det du gir den. Vi setter grensene i oppsettet og skriver dem ned.")])

add("personal-content",
 title="Personlig innhold",
 tag="Privat · Innhold",
 lead="Tekstene du trenger om deg selv, skrevet én gang og gjenbrukbare.",
 audience=["Folk som skal presentere seg og aldri liker resultatet",
           "Frilansere som trenger samme tekst i fem lengder",
           "Alle som skriver «litt om meg» om igjen hver gang"],
 problem="De fleste skriver om seg selv fra bunnen hver gang det trengs — til profilen, til nettsiden, til søknaden, til foredraget. Fem varianter, alle litt forskjellige, ingen helt god.",
 solution="Én tekst skrives godt, i fire lengder: femti ord, hundre og femti, tre hundre, og en full side. Samme sannhet, samme stemme, klippet til der det skal brukes.",
 process=[("Samtale","Førtifem minutter. Hva du gjør, for hvem, og hva du vil huskes for."),
          ("Utkast","Full lengde først — det korte klippes fra det, aldri motsatt."),
          ("Lengder","Femti, hundre og femti, tre hundre ord og én side."),
          ("To runder",""),
          ("Overlevering","Alle lengder i et dokument du kan kopiere fra.")],
 delivers=["Fire lengder av samme presentasjon",
           "Én biografi i tredjeperson til programmer og omtaler",
           "Tre varianter av overskrift",
           "Alt i ett redigerbart dokument"],
 extras=["LinkedIn-profil bygget på tekstene",
         "Personlig nettside som bruker dem",
         "Sosialt innhold i samme stemme"],
 faq=[("Skriver dere som meg eller som dere?","Som deg. Vi tar opp samtalen og skriver fra hvordan du faktisk snakker."),
      ("Kan jeg få det på engelsk også?","Ja, skrevet separat. En oversatt presentasjon leses som oversatt.")])

# ---------------- BEDRIFT ----------------
add("website",
 title="Nettside",
 tag="Bedrift · Web",
 lead="En nettside teamet ditt kan vedlikeholde uten å ringe noen.",
 audience=["Små bedrifter med en side ingen har rørt siden 2021",
           "Nystartede som trenger noe før første kunde",
           "Alle som betaler for et byrå hver gang en pris skal endres"],
 problem="De fleste bedriftssider dør av vedlikehold. De bygges av noen andre, i et system ingen internt kan, og etter et år tør ingen røre dem. Da blir siden et arkiv over det selskapet var, ikke det det selger.",
 solution="Spørsmålet er omfang, ikke teknologi. Selger du én ting, vil en landingsside slå en femsiders nettside. Vi setter omfanget først, bygger deretter, og lærer opp den hos dere som skal endre priser og tekster.",
 process=[("Omfang","Hva siden skal få folk til å gjøre, og hvor mange sider det faktisk krever."),
          ("Struktur","Sidekart, hva som ligger hvor, hva som kuttes."),
          ("Design","Mobil først, på merkevaren deres eller en vi setter."),
          ("Bygg","Rask, tilgjengelig, og redigerbar av dere."),
          ("Innhold","Skrevet av oss eller av dere, avklart før vi starter."),
          ("Opplæring og overlevering","To timer og en skriftlig veiledning.")],
 delivers=["Responsiv nettside i avtalt omfang",
           "Redigerbar av dere, med skriftlig veiledning",
           "Grunnleggende SEO: titler, beskrivelser, strukturerte data, sitemap",
           "Kontaktskjema med e-postvarsling",
           "Domene, drift og SSL satt opp",
           "Kildefiler overlevert"],
 extras=["SEO-arbeid etter lansering","Innhold som fast avtale","E-handel som neste steg"],
 faq=[("Bruker dere WordPress?","Bare hvis dere trenger det. For de fleste er en statisk side raskere, tryggere og billigere å drifte."),
      ("Hvem eier filene?","Dere. Alt overleveres, inkludert kildefiler og tilganger.")])

add("landing",
 title="Landingsside",
 tag="Bedrift · Web",
 lead="Én side med én oppgave: at den som kommer, gjør det ene du vil.",
 audience=["Bedrifter som kjører annonser mot en forside som ikke konverterer",
           "Lansering av ett produkt eller ett arrangement",
           "Alle som får trafikk og ingen henvendelser"],
 problem="En forside gjør fem ting. En annonse lover én. Sender du annonsetrafikk til forsiden, betaler du for å forvirre folk — de leter etter det de ble lovet og finner en meny.",
 solution="Én side, ett løfte, én handling. Overskriften gjentar annonsen, brødteksten fjerner tvilen, skjemaet spør om det minste vi trenger. Ingen meny som frister til å gå et annet sted.",
 process=[("Løftet","Hva annonsen sier, ordrett."),
          ("Innvendingene","De fem grunnene folk ikke handler."),
          ("Struktur","Rekkefølgen som svarer dem, i den rekkefølgen de oppstår."),
          ("Bygg","Én side, rask, mobil først."),
          ("Måling","Hva vi teller, og hva som ville regnes som suksess.")],
 delivers=["Én landingsside, responsiv",
           "Skjema med varsling og takkeside",
           "Måling satt opp med definerte mål",
           "En variant av overskrift og handlingsknapp for test"],
 extras=["SEO for den samme siden","Annonsetekst som matcher","Rapportering på konvertering"],
 faq=[("Hvor mange varianter tester dere?","To. Flere krever mer trafikk enn de fleste har."),
      ("Kan siden ligge på vårt domene?","Ja, som eget underområde. Vi setter det opp.")])

add("ecommerce",
 title="Nettbutikk",
 tag="Bedrift · Web",
 lead="Bygget rundt kassen, ikke rundt temaet — Vipps og kort fra dag én, på en plattform dere eier selv.",
 audience=["Bedrifter som selger fysiske varer i dag uten nettbutikk",
           "Butikker som får trafikk men få fullførte kjøp",
           "Alle som taper kunder i de siste tre klikkene"],
 problem="De fleste små nettbutikker taper kunden i kassen, ikke i utvalget. Frakt som først dukker opp på siste side, tvungen registrering, og en betalingsmetode kunden ikke bruker. Utseendet var aldri problemet.",
 solution="Vi bygger fra kassen og utover: Vipps og kort først, frakt vist tidlig, kjøp uten konto, og MVA satt riktig fra dag én. Produktsidene kommer etter at kjøpsløpet fungerer.",
 process=[("Kjøpsløp","Fra første klikk til bekreftelse, tegnet ut før noe bygges."),
          ("Betaling","Vipps, kort og lommebøker satt opp og testet med ekte kort."),
          ("Frakt og MVA","Satser, soner og terskler avklart med regnskapsfører."),
          ("Produkter","Struktur, varianter, lager."),
          ("Bygg og test","Hele løpet gjennomført fra en fremmed enhet."),
          ("Opplæring","Hvordan dere legger inn og endrer selv.")],
 delivers=["Nettbutikk med fungerende kasse",
           "Vipps og kortbetaling satt opp",
           "Frakt- og MVA-regler konfigurert",
           "Produktstruktur med varianter",
           "Ordrevarsling og kvittering",
           "Opplæring og skriftlig veiledning"],
 extras=["EHF-faktura for bedriftskunder","SEO for produktsidene","Rapportering på salg og frafall"],
 faq=[("Hvilken plattform?","Den som passer utvalget og volumet. Vi anbefaler etter at vi har sett varene, ikke før."),
      ("Kan vi selge til utlandet?","Ja. Da må MVA og frakt settes per marked, og det avklares med regnskapsfører først.")])

add("branding",
 title="Merkevare",
 tag="Bedrift · Merkevare",
 lead="Et navn, et merke og et system dere kan bruke overalt uten å spørre.",
 audience=["Nystartede som trenger alt et selskap blir bedt om",
           "Bedrifter der hver ansatt har sin egen versjon av logoen",
           "Alle som skal bytte navn eller slå sammen to"],
 problem="En logo er ikke en merkevare. Problemet melder seg når noen skal lage en faktura, en annonse og en skiltplate — og det finnes tre ulike røde, to fonter og ingen som vet hvilken som er riktig.",
 solution="Et lite system framfor en stor manual: merket i alle formater, to fonter, fire farger med bruksregler, og maler for det dere faktisk lager ukentlig. Kort nok at folk følger det.",
 process=[("Grunnlag","Hva selskapet gjør, for hvem, og hva det ikke er."),
          ("Retning","To retninger vist, én valgt. Ikke tolv."),
          ("Merket","Primær, sekundær, ikon, negativ, alle formater."),
          ("Systemet","Farger med kontrastkrav, to fonter, avstandsregler."),
          ("Malene","Faktura, presentasjon, sosiale medier, e-postsignatur."),
          ("Overlevering","Filer, regler på få sider, og rettighetene skriftlig.")],
 delivers=["Merket i SVG, PNG og PDF, alle varianter",
           "Fargesystem med kontrastverdier",
           "To fonter med lisensstatus avklart",
           "Maler for faktura, presentasjon og sosiale medier",
           "Retningslinjer på få sider, ikke førti",
           "Alle rettigheter overført skriftlig"],
 extras=["Nettside på den nye merkevaren","Skilt- og trykkfiler","Innhold i den nye stemmen"],
 faq=[("Får vi eierskap til logoen?","Ja, skriftlig, ved sluttoppgjør. Det står i leveransen."),
      ("Er fontene lisensiert?","Vi velger fonter dere kan bruke lovlig, og oppgir lisensen. Gratis der det holder, betalt der det kreves.")])

add("logo",
 title="Logo og grafikk",
 tag="Bedrift · Merkevare",
 lead="Ett merke som fungerer i tjue piksler og på en vegg.",
 audience=["Nystartede som trenger et merke og ikke et helt system",
           "Bedrifter med en logo som blir uleselig i liten størrelse",
           "Alle som trenger filene de aldri fikk fra forrige designer"],
 problem="De fleste logoer feiler i to størrelser: som favicon og på en fasade. Et merke tegnet på skjerm i femti prosent zoom ser bra ut nøyaktig der og ingen andre steder.",
 solution="Merket tegnes i vektor og testes i de størrelsene det skal brukes i — favicon, profilbilde, brevhode, skilt. Du får alle varianter og filene, ikke bare en PNG.",
 process=[("Grunnlag","Hva merket skal signalisere, og hva det ikke skal."),
          ("Skisser","Tre retninger, i svart og hvitt først."),
          ("Valg og foredling","Én retning, to runder."),
          ("Varianter","Primær, ikon, horisontal, negativ."),
          ("Overlevering","Alle formater, med rettighetene skriftlig.")],
 delivers=["Merket i SVG, PDF, PNG og ICO",
           "Primær, ikon, horisontal og negativ variant",
           "Testet som favicon, profilbilde og i stort format",
           "Bruksregler på én side",
           "Rettigheter overført skriftlig"],
 extras=["Fullt merkevaresystem","Maler for faktura og presentasjon","Nettside på merket"],
 faq=[("Hvor mange forslag får vi?","Tre retninger, én videreføres. Tjue forslag er en måte å utsette en beslutning."),
      ("Kan vi varemerkeregistrere det?","Vi tegner originalt, og vi kan levere filene i formatet Patentstyret krever. Selve søknaden er en juridisk vurdering.")])

add("social-media",
 title="Sosiale medier",
 tag="Bedrift · Innhold",
 lead="En måned planlagt i én sitting. Publisert etter plan, ikke etter innfall.",
 audience=["Bedrifter der markedsføring er en oppgave ingen eier",
           "Butikker og tjenester med lokale kunder",
           "Alle som publiserer tre ganger og deretter stopper"],
 problem="Kontoen dør ikke av dårlig innhold. Den dør av at beslutningen om hva som skal publiseres tas daglig, av noen som har en annen jobb.",
 solution="Beslutningen tas én gang i måneden. Kalender, tekst og bilder ferdig på forhånd, og publisering etter plan. Målet er at det kommer noe jevnt — ikke at noe blir viralt.",
 process=[("Retning","Hvem dere snakker til og hva de skal huske."),
          ("Kalender","Innlegg for måneden, tema per uke."),
          ("Tekst og design","I deres stemme, på deres merkevare."),
          ("Publisering","Etter plan, av oss eller av dere."),
          ("Månedsrapport","Hva som fungerte, og hva vi endrer neste måned.")],
 delivers=["Innholdskalender per måned",
           "Ferdige innlegg med tekst og bilde",
           "Publisering etter avtalt plan",
           "Månedlig rapport i klarspråk"],
 extras=["Annonsering på det som fungerer","Fotoredigering av eget materiale","Landingsside som destinasjon"],
 faq=[("Hvor mange innlegg i måneden?","Det avtales, og færre og bedre slår flere og tynnere."),
      ("Svarer dere på kommentarer?","Som tillegg, ja — med en liste over hva vi ikke svarer på uten dere.")])

add("seo",
 title="Søkemotoroptimalisering",
 tag="Bedrift · Synlighet",
 lead="Bli funnet på det folk faktisk søker på, ikke på det dere kaller det.",
 audience=["Bedrifter med en side som ikke dukker opp på eget fagområde",
           "Lokale tjenester der kundene søker før de ringer",
           "Alle som betaler for annonser fordi organisk trafikk er null"],
 problem="To atskilte problemer blandes ofte sammen: ingen kommer, og de som kommer gjør ingenting. SEO løser det første. Den løser ikke det andre, og det er verdt å si før noen betaler for det.",
 solution="Vi finner søkene som faktisk har volum og intensjon i deres marked, retter det tekniske som stopper indeksering, og skriver om sidene som skal rangere. Det som ikke kan rangere, sier vi at ikke kan rangere.",
 process=[("Kartlegging","Hva dere rangerer på nå, og hva som er realistisk."),
          ("Søkeord","Volum og intensjon, ikke bare volum."),
          ("Teknisk","Indeksering, hastighet, strukturerte data, mobil."),
          ("Innhold","Sidene som skal rangere, skrevet om."),
          ("Måling","Utgangspunkt satt før arbeid, målt etter tre måneder.")],
 delivers=["Søkeordkartlegging med volum og intensjon",
           "Teknisk gjennomgang med prioritert liste",
           "Omskrevne sider for de valgte søkene",
           "Strukturerte data og sitemap",
           "Utgangspunkt og målemetode skriftlig"],
 extras=["Innhold som fast avtale","Landingsside for det som konverterer","Rapportering hver måned"],
 faq=[("Hvor lang tid tar det?","Tre til seks måneder før noe er målbart. Alle som lover raskere selger noe annet."),
      ("Garanterer dere plassering?","Nei. Ingen kan, og de som sier det bryter Googles retningslinjer.")])

add("content",
 title="Innhold",
 tag="Bedrift · Innhold",
 lead="Tekstene som svarer på det kundene spør om før de kjøper.",
 audience=["Bedrifter som forklarer det samme på telefon hver uke",
           "Fagfolk som ikke får skrevet ned det de kan",
           "Alle som har en blogg med to innlegg fra 2022"],
 problem="Innhold som skrives for å fylle en kalender leses ikke og selger ikke. Innhold som svarer på et reelt spørsmål gjør begge — men det spørsmålet må komme fra kundene, ikke fra en søkeordliste.",
 solution="Vi starter med spørsmålene dere faktisk får, i den rekkefølgen de koster mest tid. Hvert stykke svarer på ett spørsmål helt, og nevner tjenesten som gjør jobben når svaret ikke er nok.",
 process=[("Spørsmålene","Hentet fra e-post, telefon og salgssamtaler."),
          ("Prioritering","Det som koster mest tid å forklare, først."),
          ("Utkast","Ett spørsmål, ett svar, ferdig svart."),
          ("Fagsjekk","Dere retter fakta; vi retter språk."),
          ("Publisering","Med intern lenking og strukturerte data.")],
 delivers=["Avtalt antall tekster per måned",
           "Ett spørsmål besvart per tekst",
           "Intern lenking til tjenestesidene",
           "Strukturerte data der det passer",
           "Kort månedlig oversikt over hva som leses"],
 extras=["SEO for de samme tekstene","Sosialt innhold som deler dem","Nyhetsbrev bygget på dem"],
 faq=[("Bruker dere AI?","Til research og utkast, ja. Ferdig tekst leses, rettes og godkjennes av et menneske, og fagsjekken er alltid deres."),
      ("Kan vi skrive selv og få redigering?","Ja, og det er ofte billigere og bedre. Vi tar rollen som redaktør.")])

add("ai-automation",
 title="AI-automatisering",
 tag="Bedrift · AI",
 lead="Den repeterende delen av uken overlatt til noe som gjør den likt hver gang.",
 audience=["Bedrifter der en person bruker dagen på å flytte data",
           "Selskaper som sender samme tilbud i tjue varianter",
           "Alle som har prøvd å automatisere og gitt opp"],
 problem="De fleste automatiseringsprosjekter feiler fordi de starter med verktøyet. Riktig start er oppgaven du gjør mer enn fem ganger i uken og misliker mest — og den finnes ikke i en verktøyliste.",
 solution="Én arbeidsflyt om gangen, valgt etter tid spart og irritasjon fjernet. Bygget, dokumentert og overlevert, med en liste over hva den ikke skal gjøre. Én fungerende automatisering slår en plattform ingen tar i bruk.",
 process=[("Tidsmåling","To uker av hva som faktisk gjentas."),
          ("Valg","Den ene oppgaven med best forhold mellom tid og risiko."),
          ("Bygg","Arbeidsflyten, med feilhåndtering som varsler et menneske."),
          ("Grenser","Hva den aldri gjør alene, skrevet ned."),
          ("Prøveuke","Under tilsyn, med daglig gjennomgang."),
          ("Dokumentasjon og opplæring","")],
 delivers=["Én arbeidsflyt i drift",
           "Feilhåndtering med navngitt ansvarlig",
           "Skriftlig liste over hva den ikke har lov til",
           "Dokumentasjon og opplæring",
           "Måling av tid spart mot utgangspunktet"],
 extras=["Neste arbeidsflyt, én om gangen","AI-ansatte for kundekontakt","Rapportering på gevinsten"],
 faq=[("Erstatter dette folk?","Det erstatter en oppgave, ikke en person. Hvis svaret er nedbemanning, si det før vi begynner — det endrer hva vi bygger."),
      ("Hva om den gjør feil?","Den varsler et menneske framfor å gjette. Det er en designbeslutning, ikke en innstilling.")])

add("chatbot",
 title="Chatbot",
 tag="Bedrift · AI",
 lead="Svarer på det kundene faktisk spør om, og sender samtalen videre til en person når den må.",
 audience=["Bedrifter som får de samme tjue spørsmålene hver uke",
           "Nettbutikker med spørsmål om frakt og retur",
           "Alle som svarer på e-post om åpningstider"],
 problem="En chatbot som ikke vet noe er verre enn ingen chatbot. Den irriterer den som spør, forsinker svaret og gir inntrykk av at selskapet ikke bryr seg.",
 solution="Den trenes på deres eget materiale, svarer bare fra det, og sier ifra når den ikke vet. Da sender den samtalen videre til en navngitt person, med hele dialogen vedlagt. Den later ikke som den er et menneske.",
 process=[("Kunnskapen","De tjue spørsmålene, med svarene dere vil gi."),
          ("Grensene","Hva den aldri skal love."),
          ("Overlevering","Hvem som tar over, og hva de får."),
          ("Bygg","På nettsiden, i deres stemme."),
          ("Prøveuker","To uker under tilsyn, svar rettet daglig."),
          ("Månedsrapport","Hva den ikke kunne svare på.")],
 delivers=["Chatbot på nettsiden, trent på deres materiale",
           "Overleveringsregler med navngitt ansvarlig",
           "Full logg over samtaler, under deres kontroll",
           "Månedsrapport over ubesvarte spørsmål",
           "To uker under tilsyn før den står alene"],
 extras=["AI-resepsjonist for telefon og melding","CRM så samtalene havner på kunden","Innhold basert på det den ikke kunne svare"],
 faq=[("Sier den at den er en bot?","Ja, i første melding. Det er både riktig og i flere markeder et krav."),
      ("Hvem eier loggene?","Dere. Lagringstid settes av dere og sletting er mulig på forespørsel.")])

add("crm",
 title="CRM og kundeflyt",
 tag="Bedrift · Drift",
 lead="Henvendelser fanget, merket og fulgt opp — uten at noe ligger en uke i en innboks.",
 audience=["Bedrifter der salg bor i en innboks og et hode",
           "Selskaper som mister henvendelser i travle uker",
           "Alle som ikke vet hvor mange tilbud som er ute"],
 problem="Uten et felles sted er oppfølging avhengig av hukommelse. Det fungerer til to travle uker på rad, og da forsvinner henvendelser stille — uten at noen oppdager det, fordi det ikke finnes noe å oppdage det i.",
 solution="Ett sted der henvendelser lander, merkes og følges opp automatisk. Konfigurert til å være enkelt nok at folk faktisk bruker det, framfor et system alle omgår.",
 process=[("Dagens flyt","Hvor henvendelser kommer inn og hvor de forsvinner."),
          ("Struktur","Faser som beskriver salget deres, ikke en mal."),
          ("Oppsett","Skjemaer, merking, automatisk oppfølging."),
          ("Personvern","Behandlingsgrunnlag, lagringstid og sletting satt opp."),
          ("Opplæring","En time, og en veiledning på én side.")],
 delivers=["CRM satt opp med deres faser",
           "Skjemaer som skriver rett inn",
           "Automatisk oppfølging med maler",
           "Personvern konfigurert: grunnlag, lagringstid, sletting",
           "Opplæring og veiledning"],
 extras=["Rapportering på pipeline","AI-salgsassistent i front","Automatisering av det som gjentas"],
 faq=[("Hvilket CRM?","Oftest ett dere har, eller et lett dere ikke vil angre på å betale for."),
      ("Er dette GDPR-riktig?","Satt opp for å være det: grunnlag registrert, lagringstid satt, sletting mulig. Hele standarden står i den juridiske informasjonen.")])

add("process-automation",
 title="Prosessautomatisering",
 tag="Bedrift · Drift",
 lead="Flere sammenkoblede oppgaver automatisert som ett program, i etapper.",
 audience=["Selskaper som har automatisert én ting og vil ha resten",
           "Bedrifter der systemene ikke snakker sammen",
           "Alle som har vokst forbi det manuell koordinering tåler"],
 problem="Punktautomatisering hjelper og slutter så å hjelpe, fordi arbeidet ikke bor i én oppgave. Ordren kommer i ett system, fakturaen i et annet, prosjektet i et tredje, og en person bruker uken på å bære data mellom dem.",
 solution="Kjeden kartlegges fra ende til ende og automatiseres som ett program: systemene koblet, data lagt inn én gang, avvik løftet til et menneske framfor å skjules. Levert i etapper, slik at verdien kommer før alt er ferdig.",
 process=[("Kartlegging","Hvert steg, system og overlevering i kjeden."),
          ("Prioritering","Der tiden og feilene faktisk er."),
          ("Etappe én","Det mest verdifulle leddet, bygget og bevist."),
          ("Kobling","Systemene integrert, data lagt inn én gang."),
          ("Avvik","Hva maskinen må eskalere, og til hvem."),
          ("Dokumentasjon og opplæring","")],
 delivers=["Prosesskart fra ende til ende",
           "Automatisering i etapper, verdi ved hver",
           "Systemintegrasjoner",
           "Avvikshåndtering med navngitte ansvarlige",
           "Dokumentasjon og opplæring",
           "Kvartalsvis gjennomgang i ett år"],
 extras=["Rapportering på hele kjeden","CRM som ryggrad","Chatbot i kundeenden"],
 faq=[("Må vi bytte systemer?","Vanligvis ikke. Vi kobler det dere har før vi foreslår at dere kjøper noe."),
      ("Hva om en etappe ikke lønner seg?","Etappevis levering finnes nettopp for at dere kan stoppe etter en etappe og beholde det som virker.")])

add("reporting",
 title="Rapportering og dataanalyse",
 tag="Bedrift · Drift",
 lead="Ett dashbord som svarer på de tre spørsmålene dere faktisk stiller hver måned.",
 audience=["Bedrifter med data på fem steder og svar på ingen",
           "Eiere som setter sammen de samme tallene manuelt hver måned",
           "Styrer som ber om et tall ingen kan produsere raskt"],
 problem="De fleste selskaper har rikelig med data og ingen svar, fordi tallene bor i ulike systemer og å samle dem er en manuell jobb noen gjør dårlig én gang i måneden. Da tas beslutninger på inntrykk.",
 solution="Tre spørsmål avtales først — de dere virkelig stiller — og så bygges dashbordet som svarer på nøyaktig dem, oppdatert automatisk. Ikke førti grafer ingen leser. Definisjonene skrives ned, slik at tallet betyr det samme neste kvartal.",
 process=[("De tre spørsmålene","Avtalt og nedskrevet før noe bygges."),
          ("Kilder","Hvor hvert tall faktisk kommer fra."),
          ("Definisjoner","Hva som teller som et salg, et lead, en kunde — skriftlig."),
          ("Bygg","Dashbord med automatisk oppdatering."),
          ("Lesetime","Hvordan det tolkes og hva som gjøres med det.")],
 delivers=["Dashbord som svarer på de avtalte spørsmålene",
           "Automatisk oppdatering av data",
           "Skriftlige definisjoner av hvert mål",
           "Månedlig oppsummering i klarspråk",
           "Én lesetime med opplæring"],
 extras=["CRM som ren datakilde","Prosessautomatisering av innsamlingen","SEO- og kampanjedata inkludert"],
 faq=[("Hvilket verktøy?","Det som passer data og budsjett. Ofte noe dere allerede betaler for."),
      ("Kan regnskapstall inkluderes?","Ja, med lesetilgang dere kontrollerer.")])

add("ai-receptionist",
 title="AI-resepsjonist",
 tag="Bedrift · AI-ansatt",
 lead="Svarer på hver telefon, melding og bestilling — klokken tre om natten like villig som klokken elleve.",
 audience=["Klinikker, salonger, verksteder og håndverkere som taper bestillinger til en telefon som ringer",
           "Små team der den som er nærmest svarer, dårlig, midt i en oppgave",
           "Alle med kunder som skriver om kvelden og kjøper av den som svarer først"],
 problem="Et tapt anrop er sjelden en kunde som ringer tilbake. De ringer det neste navnet på lista. De fleste små bedrifter vet dette og mister likevel en tredjedel av anropene, fordi den som kunne svart holder en drill, en kunde eller et barn.",
 solution="En resepsjonist på vakt hver time hele året. Den svarer telefon og meldingskanaler i deres stemme, kjenner åpningstider, priser og tjenester, bestiller rett inn i kalenderen, og gir det den ikke kan avgjøre til en navngitt person med hele samtalen vedlagt.",
 process=[("Hva den må vite","Tjenester, priser, åpningstider, de ti spørsmålene dere svarer på hver uke, og hva den aldri skal love."),
          ("Stemme","Hvordan den hilser, hvor formell den er, og hva den sier når den ikke vet."),
          ("Kalender og kanaler","Telefon, nettprat, SMS og e-post koblet til systemet dere har."),
          ("Eskalering","Hvilke situasjoner som går til et menneske umiddelbart, og til hvem."),
          ("To uker under tilsyn","Hver samtale gjennomgått av oss og av dere, og svarene rettet."),
          ("Overlevering","Utskrifter, månedsrapport, og en måte å endre hvert svar selv.")],
 delivers=["Resepsjonist på telefon, prat, SMS og e-post døgnet rundt",
           "Bestilling skrevet rett i kalenderen",
           "Eskaleringsregler med navngitte ansvarlige",
           "Full utskrift av hver samtale, under deres kontroll",
           "Månedsrapport: anrop tatt, bestillinger gjort, spørsmål ubesvart",
           "To uker under tilsyn før den står alene"],
 extras=["Norsk og engelsk på samme nummer","Chatbot på nettsiden med samme kunnskap","CRM slik at hver samtale havner på et kundekort"],
 faq=[("Vil den som ringer skjønne at det ikke er et menneske?","Ja — den sier det i hilsenen. Å late som noe annet er både galt og, for telefon, juridisk risikabelt i flere markeder."),
      ("Hva skjer når den ikke vet?","Den sier det, tar detaljene, og gir hele samtalen til personen dere har navngitt. Den har ikke lov til å gjette om priser eller ledig tid."),
      ("Hvem eier opptak og utskrifter?","Dere. Lagringstid settes av dere, sletting er mulig på forespørsel, og behandlingsgrunnlaget er registrert.")])

add("ai-sales-assistant",
 title="AI-salgsassistent",
 tag="Bedrift · AI-ansatt",
 lead="Svarer på kjøpsspørsmålet i det øyeblikket det stilles, kvalifiserer henvendelsen, og booker møtet.",
 audience=["Selskaper der henvendelser kommer utenfor arbeidstid",
           "Selgere som bruker dagen på henvendelser som aldri skulle kjøpt",
           "Bedrifter med en lang prisliste og kort tid til å forklare den"],
 problem="De fleste henvendelser tapes i gapet mellom interesse og svar. Noen spør klokken ni om kvelden, får svar klokken elleve neste formiddag, og har allerede kjøpt et annet sted. De som får raskt svar er ofte de som aldri skulle kjøpt — så det raske svaret brukes på gal person.",
 solution="En assistent som svarer umiddelbart, besvarer produkt- og prisspørsmål ordentlig, finner ut om dette er en reell mulighet ved å stille de fire spørsmålene salgsprosessen deres faktisk hviler på, og booker kvalifiserte folk i en kalender. Ukvalifiserte får et ærlig og nyttig svar framfor en jakt.",
 process=[("Tilbudet, nedskrevet","Produkter, priser, hva dere ikke selger, og hva dere ikke rabatterer."),
          ("Kvalifisering","De fire spørsmålene som avgjør om en henvendelse er verdt et møte."),
          ("Innvendinger","De seks dere hører oftest, og svaret dere vil gitt."),
          ("Overleveringspunkt","Nøyaktig hvor et menneske tar over, og hva de får."),
          ("To uker under tilsyn","Reelle henvendelser, gjennomgått daglig, svar rettet."),
          ("Rapportering","Hva som kom inn, hva som kvalifiserte, hva som ble booket, hva som ble tapt og hvorfor.")],
 delivers=["Umiddelbart svar på nettprat, e-post og meldingskanalene dere bruker",
           "Kvalifisering mot deres egne kriterier, ikke en generisk mal",
           "Møter booket i kalenderen til riktig person",
           "Skriftlig spor for hver henvendelse med grunnen til at den kvalifiserte eller ikke",
           "Månedsrapport: henvendelser, kvalifiseringsgrad, møter, vanlige innvendinger",
           "To uker under tilsyn før den står alene"],
 extras=["CRM slik at pipeline er synlig uten regneark","Landingsside bygget rundt spørsmålene den hører oftest","Dashbord som kombinerer salg og markedsdata"],
 faq=[("Vil den rabattere for å lande en avtale?","Nei. Den oppgir de publiserte prisene og har ingen myndighet til å gå under dem. Rabatt er en menneskelig beslutning."),
      ("Hva om den svarer feil om et produkt?","Den svarer bare fra materialet dere har godkjent, og sier at den skal sjekke når den blir spurt om noe utenfor. De to ukene under tilsyn finnes for å finne hullene før kundene gjør det."),
      ("Erstatter den en selger?","Den erstatter den første timen av dagen deres. Møtet, forhandlingen og relasjonen forblir menneskelige.")])

add("ai-office-assistant",
 title="AI-kontorassistent",
 tag="Bedrift · AI-ansatt",
 lead="Sorterer innboksen, skriver utkast til de rutinemessige dokumentene, purrer det alle glemmer.",
 audience=["Eiere som gjør tre timer administrasjon etter at arbeidsdagen er slutt",
           "Kontorer der én person er flaskehals for hvert dokument",
           "Team der hvert system trenger den samme informasjonen skrevet inn på nytt"],
 problem="Administrasjon er ikke vanskelig; den er ubønnhørlig. Sortere en innboks, skrive de samme tre brevene, legge en ordre inn i to systemer, huske at en faktura er ni dager forfalt. Ingenting av det krever skjønn, alt krever å bli gjort, og det gjøres nesten alltid av den hvis tid er verdt mest.",
 solution="En assistent som tar rutinelaget: innboksen sortert etter hva som krever en beslutning og hva som ikke gjør det, standarddokumentene skrevet ut fra deres egne maler, data lagt inn én gang og båret videre, og de stille purringene sendt til rett tid. Alt den produserer er et utkast til et menneske godkjenner det.",
 process=[("Tidsmåling","To uker av hva som faktisk spiser den administrative dagen."),
          ("Rutinelista","Hvilke oppgaver som er regelstyrte, hvilke som krever skjønn, og hvilke som aldri skal automatiseres."),
          ("Maler","Deres dokumenter, deres formuleringer, deres signaturblokker."),
          ("Godkjenningspunkter","Hva den får sende selv, og hva som venter på et menneske."),
          ("Bygg og kobling","Innboks, kalender, lagring og regnskap koblet."),
          ("To uker under tilsyn, deretter dokumentasjon og opplæring","")],
 delivers=["Innboksen sortert daglig i beslutt / les / ingen handling",
           "Rutinedokumenter skrevet ut fra deres maler, klare til godkjenning",
           "Data lagt inn én gang og båret inn i hvert koblet system",
           "Oppfølging og påminnelser sendt etter deres plan",
           "Navngitt liste over hva den får gjøre alene og hva den ikke får",
           "Månedlig oppsummering av timer levert tilbake til dere"],
 extras=["Prosessautomatisering for kjedene den ikke dekker alene","Rapportering slik at de tilbakeførte timene er målbare","CRM som det ene stedet kundeinformasjon bor"],
 faq=[("Kan den sende e-post som meg?","Bare det dere har satt på den godkjente lista. Alt annet venter som et utkast."),
      ("Hva med konfidensielle dokumenter?","Dere navngir mappene og kategoriene den aldri får røre, og den kan ikke nå dem. Tilgangen er avgrenset, loggført og kan trekkes."),
      ("Hvordan vet vi at den sparer tid?","Tidsmålingen i starten gir utgangspunktet, og månedsoppsummeringen rapporterer mot det. Kommer ikke timene, er svaret å stoppe — ikke å automatisere mer.")])
