# One record per service. Each becomes its own page.
# problem / solution / process / delivers / audience / extras / examples / faq
S = []
def add(**k): S.append(k)

# ---------------- PRIVATE ----------------
add(slug="cv", track="private", n="01", title="CV &amp; job applications",
 tag="Private · Applications",
 lead="A CV that gets past the screening software and still reads like a person wrote it.",
 audience=["People applying in Norway or the EEA who are getting no replies","Career changers whose experience does not map neatly onto the job title","Anyone whose CV has grown by accretion over ten years"],
 problem="Most CVs are rejected before a human sees them. Applicant-tracking systems parse the file, look for the terms in the advert, and rank what they find. A beautiful two-column layout with the job titles in a sidebar often scores zero — not because the candidate is weak, but because the file could not be read.",
 solution="The CV is rebuilt in a structure the parser can read and a person wants to read: one column, real headings, results before responsibilities, and the vocabulary of the adverts you are actually answering. You get the master document plus a short guide for tailoring it per application.",
 process=[("Send what you have","Current CV, two adverts you would apply to, and anything you are proud of that is missing from the page."),("We map it","Your experience against what those adverts screen for — gaps named honestly, not papered over."),("Rebuild","One column, results first, a number in at least half the lines."),("Tailoring guide","Which three lines to change per application, and which never to touch."),("Two revisions","One consolidated set of comments each round.")],
 delivers=["Master CV as .docx and PDF, named firstname-lastname-cv.pdf","Application letter template with the three variable blocks marked","A one-page tailoring guide","Keyword list drawn from real adverts in your field"],
 price="from kr 1 200", time="5–10 working days",
 extras=["LinkedIn optimisation — the profile recruiters actually search","Interview preparation, two sessions","English and Norwegian versions of the same CV"],
 faq=[("Will you invent experience I do not have?","No. We reframe what is true and name the gaps so you can answer them in an interview instead of being caught by them."),("Do I need a photo?","In Norway, usually not. We advise per market and supply both versions if you want the choice.")])

add(slug="linkedin", track="private", n="02", title="LinkedIn optimisation",
 tag="Private · Profile",
 lead="Headline, about and experience rewritten around what recruiters type into the search box.",
 audience=["People who want to be found rather than to apply","Freelancers and consultants selling from their profile","Anyone whose profile still says the job they left in 2021"],
 problem="LinkedIn is a search engine before it is a network. Recruiters search for skills and titles, and the profiles that surface are the ones carrying those words in the headline, the about section and the role descriptions. Most profiles carry a job title and nothing else — so they never appear.",
 solution="The profile is rewritten as a findable document: a headline that states what you do and for whom, an about section that opens with the result you produce, and experience entries that read as evidence. Written in your voice, not in the vocabulary of a motivational poster.",
 process=[("Audit","What you currently rank for, and what you should."),("Terms","The ten searches you want to appear in, taken from real postings."),("Rewrite","Headline, about, every role, skills ordered by what is searched."),("Setup notes","Open-to-work settings, featured section, what to post first."),("Two revisions","")],
 delivers=["Rewritten headline, about section and every experience entry","Prioritised skills list","Ten target search terms with rationale","A short posting plan for the first month"],
 price="from kr 1 500", time="5–10 working days",
 extras=["CV rebuilt to match the profile","Personal website as the destination the profile links to","Banner and profile image editing"],
 faq=[("Do you post for me?","No, unless you buy the social content service. We set up what to say; you keep the account."),("Norwegian or English?","Both, if your market is both. Written separately — a translation reads like a translation.")])

add(slug="personal-site", track="private", n="03", title="Personal website",
 tag="Private · Web",
 lead="A one-page site that works as your address on the internet.",
 audience=["Freelancers who currently send people to a social profile","Job seekers who want somewhere to point a QR code","Anyone who needs a stable link that outlives a platform"],
 problem="A social profile is rented ground. The platform decides who sees it, changes the layout, and can close the account. A personal site you own is the only address that stays yours — but most people never build one because the tooling assumes you want a ten-page brochure.",
 solution="One page, built as static HTML, that answers three questions: who you are, what you do, how to reach you. Fast, accessible, works on a phone, and hosted somewhere you control. No content management system to maintain and no monthly platform fee.",
 process=[("Brief","Six questions about who this page has to convince."),("Structure","What goes above the fold, what goes below, what is cut."),("Design and build","Mobile-first, on the brand you already have or one we set."),("Content","Written for you unless you would rather write it yourself."),("Handover","Files, hosting set up, and a note on how to edit it.")],
 delivers=["One-page responsive site","Contact form or mailto, your choice","Domain and hosting configured","Source files and a short edit guide","Basic SEO: title, description, structured data"],
 price="from kr 6 900", time="2–3 weeks",
 extras=["Portfolio section as a second page","Blog set up on the same domain","Multi-language version"],
 faq=[("Do I own it?","Yes. Source files, domain and hosting account are yours after handover."),("Can I edit it myself?","Yes — it is plain HTML with a written guide. If you would rather not, we quote small changes per hour.")])

add(slug="portfolio", track="private", n="04", title="Portfolio",
 tag="Private · Web",
 lead="Your work presented as cases — problem, what you did, what came of it.",
 audience=["Designers, photographers, developers, writers","Consultants who need to show method rather than output","Students building a first professional presence"],
 problem="A wall of thumbnails shows that you produced things. It does not show that you can be trusted with a budget. The buyer is trying to work out how you think, and a grid of finished images does not tell them.",
 solution="Each project is written as a short case: the problem the client had, what you actually did, and what came of it. The images support the argument rather than being the argument. Three strong cases beat twelve thin ones, and we will say so if you send twelve.",
 process=[("Selection","Which projects to show, and which to leave out."),("Case interviews","One call per project to get the problem and the result out of you."),("Writing","Each case in problem / work / result form."),("Build","Responsive gallery with the cases as the spine."),("Two revisions","")],
 delivers=["Portfolio site, three to eight cases","Case text written from your own account","Image preparation and sizing per platform","Downloadable PDF version for email"],
 price="from kr 8 500", time="3–4 weeks",
 extras=["Personal website as the front page","Photo editing for the project images","Print portfolio layout"],
 faq=[("What if my results are confidential?","We describe the shape of the result without the number, or ask the client for a figure they will approve."),("How many projects should I show?","Usually three to five. More dilutes.")])

add(slug="social-content", track="private", n="05", title="Social content",
 tag="Private · Content",
 lead="A month of posts written and designed in one pass, so posting stops being a daily decision.",
 audience=["Freelancers building an audience they can sell to","People job-hunting who want to be visible in their field","Anyone who posts twice then goes quiet for six weeks"],
 problem="Consistency beats brilliance on social, and consistency fails for a boring reason: deciding what to post is a daily decision, and daily decisions get skipped. The account goes quiet, the algorithm forgets you, and starting again costs more than continuing would have.",
 solution="A month planned in one sitting and produced in one pass. You approve the calendar, we write and design, and you have thirty days of material sitting ready. The decision is made once a month instead of once a day.",
 process=[("Positioning","What you want to be known for, in one sentence."),("Calendar","A month of subjects, mapped to the formats each platform rewards."),("Production","Copy written in your voice, visuals designed to match."),("Approval","One round of comments on the batch."),("Delivery","Files plus a posting schedule.")],
 delivers=["Monthly content calendar","12–20 posts written and designed","Platform-native formats and sizes","Caption and hashtag sets","Monthly performance note"],
 price="from kr 3 900 / month", time="First calendar in 10 days",
 extras=["Photo editing for original imagery","LinkedIn profile rewritten to match the content","Short-form video editing"],
 faq=[("Do you post it?","We can, or we hand you the files scheduled. Your account stays yours either way."),("Will it sound like me?","We write from a sample of your own writing. If the first batch does not sound like you, we rewrite it, not you.")])

add(slug="photo-editing", track="private", n="06", title="Photo editing",
 tag="Private · Imagery",
 lead="Retouching, colour and format for portraits and product shots — including files sized per platform.",
 audience=["People who need one profile photo to work everywhere","Small sellers photographing their own products","Anyone with good photographs in the wrong format"],
 problem="A good photograph in the wrong format is a bad photograph. Profile images get cropped to a circle, product shots get compressed to grey, and the same file that looks right on a laptop looks wrong on a phone.",
 solution="Editing plus format discipline: colour, exposure and retouching to a standard you approve, then export sets sized for every place the image actually appears. Skin is retouched to look like skin. Products are corrected, not invented.",
 process=[("Send the files","RAW where you have it — there is more to work with."),("Reference","One image whose treatment you like, so taste is not guessed."),("Edit","Colour, exposure, retouching, background where needed."),("Export sets","Sized per platform, named so you can find them."),("One revision round","")],
 delivers=["Edited masters at full resolution","Platform-sized exports (LinkedIn, Instagram, web, print)","Background removal where requested","Consistent treatment across the whole set"],
 price="from kr 490", time="2–5 working days",
 extras=["A commissioned shoot instead of editing existing files","Product photography for e-commerce","Content credentials written at capture"],
 faq=[("Do you use AI to generate parts of the image?","No. Retouching and correction only. Nothing is invented, and we will tell you if a request crosses that line."),("Can you fix a bad photograph?","Sometimes. We will say honestly when a reshoot is cheaper than the editing.")])

add(slug="ai-assistant", track="private", n="07", title="Personal AI assistant",
 tag="Private · AI",
 lead="A set-up that drafts your emails, applications and posts in your own voice, with the prompts saved for reuse.",
 audience=["People who write the same kind of message repeatedly","Job seekers writing twenty tailored letters","Freelancers who lose an hour a day to admin writing"],
 problem="General-purpose AI writes general-purpose text. It does not know your voice, your history or your standards, so every draft needs so much correction that it saves nothing. The tool is capable; the setup is missing.",
 solution="A configured assistant with your material behind it: a voice sample, your CV, your services, your recurring formats. The prompts are written, tested and saved, so the second use is as good as the first and you are not re-explaining yourself every session.",
 process=[("Inventory","Which writing tasks actually eat your week."),("Voice sample","We take a sample of your own writing as the reference."),("Build","Prompts written and tested against real cases."),("Handover session","One hour, live, until you can run it without us."),("Prompt library","Saved, documented, yours.")],
 delivers=["Configured assistant with your context loaded","A documented prompt library, 8–15 prompts","One live handover session","A short guide on what to check before sending"],
 price="from kr 4 500", time="1–2 weeks",
 extras=["Job application pack built on top of it","Content system for regular posting","CV and LinkedIn done first, so the assistant has good source material"],
 faq=[("Does my material train someone else's model?","No. We use training-excluded or enterprise modes and say which service is involved."),("What if I do not want AI writing for me at all?","Then do not buy this. We will suggest the CV or content service instead.")])

add(slug="personal-content", track="private", n="08", title="Blog &amp; personal content",
 tag="Private · Content",
 lead="Long-form writing that makes you findable and gives people a reason to trust you.",
 audience=["Consultants who sell expertise","People building a reputation before they need a job","Anyone whose field rewards being read"],
 problem="Short social posts disappear in a day. A written piece that answers a real question keeps working for years — it gets found in search, it gets forwarded, and it does the arguing for you before a first meeting. Most people never write one because the blank page is expensive.",
 solution="Editorial planning plus writing. We find the questions your audience actually searches, decide which ones you are credible on, and write the pieces from your own knowledge — interviewed out of you, not invented.",
 process=[("Question research","What is actually searched in your field."),("Editorial plan","Six to twelve pieces, ordered by value."),("Interview","30–45 minutes per piece; you talk, we write."),("Draft and revise","Two rounds."),("Publish","On your site, formatted, with the search basics in place.")],
 delivers=["Editorial plan","Written pieces, 900–1 500 words each","Titles and descriptions written for search","Publishing on your own site"],
 price="from kr 2 900 / piece", time="2 weeks per piece",
 extras=["Personal website to publish on","Social content derived from each piece","Newsletter set-up"],
 faq=[("Is it written by AI?","A person is responsible for every piece and it is built from your own words. We will tell you where machine assistance was used."),("Will it sound like a marketing blog?","Not if we can help it. The house style is plain and specific.")])

add(slug="career", track="private", n="09", title="Career &amp; training support",
 tag="Private · Career",
 lead="Interview preparation, salary framing and a practical plan for the next role.",
 audience=["People at an interview stage who keep not converting","Career changers who cannot explain the change convincingly","Anyone about to negotiate and dreading it"],
 problem="Getting the interview and winning it are different skills. Most people prepare by rereading their CV, then answer the salary question badly because they have never said the number out loud before.",
 solution="Two working sessions. The first rehearses the questions your field actually asks, including the awkward one about the gap or the change. The second covers the number: what to ask for, how to say it, and what to do with the silence afterwards.",
 process=[("Situation","The role, the stage, the worry."),("Session one","Interview rehearsal, recorded if you want it."),("Written notes","Your answers, tightened, so you can revise them."),("Session two","Salary framing and negotiation."),("Follow-up","One written question by email afterwards.")],
 delivers=["Two live sessions, 60 minutes each","Written answer notes for the ten likely questions","A salary framing script and a walk-away number","A dated 90-day plan"],
 price="from kr 2 400", time="Within 2 weeks",
 extras=["CV and applications rebuilt first","LinkedIn optimisation","Personal AI assistant for the application volume"],
 faq=[("Do you find jobs for me?","No. We are not a recruiter. We make you better at the process you are already in."),("Norwegian or English?","Either. Say which the interview will be in.")])

# ---------------- BUSINESS ----------------
add(slug="website", track="business", n="01", title="Website",
 tag="Business · Web",
 lead="Design and build, mobile-first, fast and accessible, with a structure your own team can maintain.",
 audience=["Small and mid-sized companies whose site was built once and abandoned","Companies whose site is slow, unreadable on a phone, or both","Organisations that need to meet accessibility obligations"],
 problem="Most company websites fail for one of three reasons: nobody can update them without calling an agency, they take four seconds to load on a phone, or they explain the company rather than the offer. The visitor leaves before the argument starts.",
 solution="A site built around what you sell, in a structure your team can maintain. Fast because it is not carrying six analytics scripts. Accessible because that is a legal obligation in Norway and the EEA, not a nice-to-have. Written so a visitor understands the offer in the first screen.",
 process=[("Brief","Six questions, four minutes. It replaces the first meeting."),("Structure","Sitemap and page purposes agreed in writing before any design."),("Design","Two directions, one chosen, then built out."),("Build","Mobile-first, tested on real devices, accessibility pass."),("Content","Written for you, or edited if you write it."),("Review","One link, one place to comment, two rounds."),("Handover","Source, accounts, documentation and a training session.")],
 delivers=["Designed and built site, responsive","Content written or edited","Accessibility pass to WCAG 2.2 AA — above the WCAG 2.0 AA the law requires of a private business in Norway","Performance budget met on mobile","Analytics that respect privacy law","Source files, accounts and a handover session","30 days of support after delivery"],
 price="from kr 24 000", time="4–8 weeks",
 extras=["SEO programme on top of the launch","Blog and content retainer","E-commerce","Multi-language build"],
 faq=[("Which platform?","Whichever you can maintain. Often static or a light CMS. We do not push a platform that pays us a commission."),("Do we own it?","Yes — source, domain, hosting and accounts transfer to you on full payment."),("What about accessibility?","Built in, not added. Keyboard, contrast, semantic structure and reduced-motion support are part of the delivery.")])

add(slug="landing", track="business", n="02", title="Landing page",
 tag="Business · Web",
 lead="One page, one action, written and measured for conversion.",
 audience=["Campaigns and launches with a single offer","Companies spending on ads that land on a homepage","Anyone testing whether a product has buyers"],
 problem="Paid traffic sent to a homepage converts badly, because a homepage is built to serve everyone and a visitor from an advert wants one thing. Every extra link on that page is an exit.",
 solution="A single page with a single action. The advert's promise is repeated in the first line, the objections are answered in the order people raise them, and there is exactly one thing to do. Measured, so you know whether it worked.",
 process=[("Offer","What is being sold and to whom, in one sentence."),("Objections","The five reasons people will not act, listed."),("Write","The page as an argument, not a brochure."),("Build","Fast, mobile-first, one action."),("Measure","Goal tracking set up before launch, not after.")],
 delivers=["One-page site, responsive","Copy written for the offer","Conversion goal tracking configured","A/B variant of the headline if wanted","Launch checklist"],
 price="from kr 9 900", time="1–2 weeks",
 extras=["SEO for the organic version of the same page","Social content for the campaign","CRM flow to catch and follow up the leads"],
 faq=[("How fast can it be live?","Five working days if the offer is decided and the content exists."),("Will it convert?","If your offer is the problem rather than your page, you hear that before anything is built — not after.")])

add(slug="ecommerce", track="business", n="03", title="E-commerce",
 tag="Business · Web",
 lead="Product structure, checkout, payment and shipping set up on a platform you actually own.",
 audience=["Makers and small brands selling direct","Shops moving off a marketplace","Companies whose current checkout loses people at the last step"],
 problem="Most small shops lose customers in the last three clicks: an unexpected shipping cost, a forced account, or a payment method the customer does not use. The catalogue is fine; the checkout is where the money leaks.",
 solution="A shop built around the checkout rather than around the theme. Product structure that supports search and filtering, shipping and VAT configured properly for Norway and the EEA, and the payment methods your customers actually use — including Vipps.",
 process=[("Catalogue","Product structure, variants, attributes."),("Platform","Chosen for what you sell and who maintains it."),("Build","Storefront, categories, product pages."),("Checkout","Payment, shipping, VAT, returns flow."),("Test","Real transactions end to end before launch."),("Handover","Training for whoever runs it daily.")],
 delivers=["Configured shop with your catalogue loaded","Checkout with card, Vipps and invoice where relevant","Shipping and VAT rules for NO and EEA","Order and returns flow documented","Training session for your team"],
 price="from kr 39 000", time="6–10 weeks",
 extras=["Product photography and editing","SEO for category and product pages","CRM and abandoned-basket flows","Reporting dashboard"],
 faq=[("Shopify, WooCommerce or something else?","Decided by your catalogue size, your team and your margins — not by our preference."),("Can you migrate our existing shop?","Yes, including URLs and redirects so the search rankings survive.")])

add(slug="branding", track="business", n="04", title="Branding",
 tag="Business · Brand",
 lead="Positioning, tone, colour and type — a system your own people can apply without asking us.",
 audience=["Companies whose materials look like they came from four different firms","New companies that need an identity before they need a website","Businesses whose offer has changed but whose brand has not"],
 problem="A logo is not a brand. Without a system — what you say, how you say it, which colours and type carry it — every new document is a fresh decision, and the decisions drift. Six months later nothing matches and nobody knows which version is correct.",
 solution="A positioning statement your team can repeat, a tone of voice with real examples, and a visual system with the rules written down. Built so an employee who has never met us can produce something on-brand on their first day.",
 process=[("Discovery","What you sell, to whom, against whom."),("Positioning","One sentence, tested against your real competitors."),("Tone","With sample sentences — what to say, what never to say."),("Visual system","Colour, type, spacing, imagery direction."),("Guide","Written so a new employee can use it unaided."),("Two revisions","")],
 delivers=["Positioning statement and messaging framework","Tone-of-voice guide with examples","Colour, typography and layout system","Templates: document, presentation, social","Brand guide as PDF and web page"],
 price="from kr 28 000", time="4–6 weeks",
 extras=["Logo and mark design","Website rebuilt on the new system","Social media applied to the new identity"],
 faq=[("Do we get a logo?","Logo design is a separate service so you can buy either alone. Bought together, they are quoted as one project."),("Will it survive us changing direction?","A good system carries a change of offer. We build for that rather than for a campaign.")])

add(slug="logo", track="business", n="05", title="Logo &amp; graphic design",
 tag="Business · Brand",
 lead="Mark, variants, and every file format you will ever be asked for, with a short usage guide.",
 audience=["New companies","Businesses whose logo exists only as a low-resolution JPEG","Anyone who has been asked for a vector file and could not supply it"],
 problem="Most small companies own a logo they cannot use: one file, one colour, wrong format, no version that works on a dark background or at 16 pixels. Every printer, platform and partner asks for something the company does not have.",
 solution="A mark designed to work at every size it will actually appear at, delivered in every format you will be asked for, with a short guide covering the four rules that keep it consistent.",
 process=[("Brief","Eleven questions. The AI Studio brief builder does most of it."),("Directions","Three concepts, each with a reason."),("Refinement","One direction developed properly."),("Variants","Horizontal, stacked, mark-only, one-colour, inverted."),("Files and guide","")],
 delivers=["Primary logo plus four variants","SVG, PNG, PDF, EPS, favicon and app icon","Colour values in HEX, RGB, CMYK and Pantone","One-page usage guide","Social profile and cover images"],
 price="from kr 12 000", time="2–4 weeks",
 extras=["Full branding system","Business card and stationery","Signage and vehicle artwork"],
 faq=[("How many concepts?","Three, then one is developed. More than three is a way of avoiding a decision."),("Do we own the copyright?","The economic rights transfer to you on full payment. Rejected concepts stay with us.")])

add(slug="social-media", track="business", n="06", title="Social media",
 tag="Business · Content",
 lead="Monthly content calendar, designed posts and platform-native formats. Reporting each month.",
 audience=["Companies posting whenever someone remembers","Businesses whose social looks nothing like their website","Teams with no one owning the account"],
 problem="Company social media usually fails on rhythm, not on ideas. Posting is nobody's actual job, so it happens in bursts, the tone changes with whoever posted, and the account reads as neglected — which is worse than not having one.",
 solution="A monthly calendar produced in one pass, on-brand, in the formats each platform rewards. You approve once a month. Reporting tells you what worked, in language you can act on.",
 process=[("Positioning","What the account is for — sales, recruitment, or credibility."),("Calendar","A month of subjects with formats per platform."),("Production","Copy and design, on-brand."),("Approval","One consolidated round."),("Publish and report","Scheduled, then measured monthly.")],
 delivers=["Monthly content calendar","16–24 designed posts","Platform-native formats and sizes","Scheduling","Monthly report with what to do next"],
 price="from kr 7 900 / month", time="First calendar in 10 days",
 extras=["Photography for original imagery","Short-form video","Paid campaign management"],
 faq=[("Minimum term?","Three months. One month tells you nothing."),("Who owns the accounts?","You do, always. We work inside your accounts, never our own.")])

add(slug="seo", track="business", n="07", title="SEO",
 tag="Business · Growth",
 lead="Technical fixes first, then structure and content — with a written plan you can hand to anyone.",
 audience=["Companies invisible in search for the terms they sell on","Shops paying for ads to reach customers who would have found them free","Anyone who has bought SEO before and cannot say what was done"],
 problem="SEO is sold as a mystery and delivered as a monthly invoice. Meanwhile the site has four pages competing for the same term, no title tags, and a mobile load time that fails before anything else matters.",
 solution="Technical problems fixed first, because content on a broken site is wasted. Then structure — one page per thing you sell — then the writing. Everything documented, so you can hand the plan to another supplier or your own team and they can continue it.",
 process=[("Audit","Technical, structural and content, written down."),("Fixes","Titles, descriptions, speed, indexing, canonicals."),("Structure","One page per offer; internal links from strong pages to new."),("Content plan","The questions your buyers search, prioritised."),("Measure","Search Console, three tracked goals, monthly reading.")],
 delivers=["Written audit with prioritised fixes","Technical fixes implemented","Title and description set for every page","Content plan for the next six months","Search Console and analytics configured","Monthly report for three months"],
 price="from kr 8 900", time="3–6 weeks, then monthly",
 extras=["Blog and content retainer to execute the plan","Landing pages for the commercial terms","E-commerce category optimisation"],
 faq=[("How long until it works?","Technical fixes show in weeks; content ranks in months. Anyone promising page one in thirty days is selling something else."),("Do you guarantee rankings?","No, and neither can anyone. We guarantee the work, documented.")])

add(slug="content", track="business", n="08", title="Blog &amp; content",
 tag="Business · Content",
 lead="Editorial planning and writing that answers what customers search for, in your language.",
 audience=["Companies with an SEO plan and nobody to execute it","Businesses whose expertise never leaves the building","Firms whose sales calls repeat the same explanation weekly"],
 problem="The questions your salespeople answer on every call are the same questions people type into search. Answering them once, publicly and well, does the selling before the call. Most companies never do it because writing is nobody's job.",
 solution="A monthly editorial pipeline: questions researched, pieces planned, your own experts interviewed, drafts written and published. You supply thirty minutes of knowledge per piece; we supply everything else.",
 process=[("Question research","What is searched, and what your sales team is asked."),("Editorial plan","Rolling three-month view."),("Interview","30–45 minutes with whoever knows."),("Write and revise","Two rounds."),("Publish","Formatted, with search basics and internal links.")],
 delivers=["Rolling editorial plan","2–4 pieces a month, 900–1 500 words","Titles and descriptions written for search","Internal linking to your commercial pages","Monthly performance note"],
 price="from kr 5 900 / month", time="First piece in 2 weeks",
 extras=["SEO audit and technical fixes first","Social content derived from each piece","Newsletter"],
 faq=[("Do you write it with AI?","A person is responsible for every piece and it is built on your experts' words. We disclose machine assistance on request."),("Norwegian or English?","Either or both, written separately.")])

add(slug="ai-automation", track="business", n="09", title="AI automation",
 tag="Business · AI",
 lead="The repetitive parts of the week — quoting, sorting, following up — handed to a workflow that runs itself.",
 audience=["Companies where one person is the bottleneck for a routine task","Businesses answering the same enquiry by hand every day","Teams whose 'system' is a spreadsheet and a good memory"],
 problem="Every small company has two or three tasks that eat hours and require no judgement: retyping enquiries, sorting attachments, sending the same follow-up. They never get automated because the person doing them has no time to automate them.",
 solution="One task, mapped and automated properly, with a human check where it matters. It starts with the task you do most and hate most, because one working automation earns you more than a platform nobody adopts.",
 process=[("Process mapping","The task as it actually happens, not as documented."),("Scope","What is automated, what stays human, and why."),("Build","One workflow, in tools you already pay for where possible."),("Test","Run in parallel with the manual process until it is trusted."),("Documentation","Written so it survives the person who requested it leaving.")],
 delivers=["Process map of the current work","One automation built, tested and live","Human checkpoints where judgement is needed","Written documentation and a handover session","30 days of adjustment after go-live"],
 price="from kr 14 000", time="3–6 weeks",
 extras=["Chatbot for the incoming half of the same process","CRM flows","Reporting dashboard on the output","Business process automation across several tasks"],
 faq=[("Does our data train a model?","No. Training-excluded or enterprise modes only, and you get the name of every service used."),("What if it breaks?","It is documented and it fails to a human, not to silence. You get 30 days of support included, and a retainer after that if you want one.")])

add(slug="chatbot", track="business", n="10", title="Chatbot",
 tag="Business · AI",
 lead="A support and sales assistant trained on your own documents, with a handover to a person built in.",
 audience=["Companies answering the same twenty questions forever","Shops losing enquiries outside office hours","Teams whose inbox is the real bottleneck"],
 problem="Generic chatbots make companies look worse. They answer confidently and wrongly, they cannot escalate, and the customer leaves more annoyed than if there had been no chat at all.",
 solution="A bot trained only on your own documents, that says it does not know rather than inventing, and hands over to a person on anything unclear. Scoped to what it can genuinely answer — which is usually more than you expect and less than a vendor will promise.",
 process=[("Question inventory","What is actually asked, from your inbox."),("Source documents","What the bot is allowed to answer from."),("Build","Scope, tone, refusal behaviour, escalation."),("Test","Against real historical questions."),("Launch","With a human escalation path that works.")],
 delivers=["Configured assistant on your site","Trained on your documents only","Escalation to email or a person","Conversation log and monthly summary","Documented update process"],
 price="from kr 16 000", time="3–5 weeks",
 extras=["AI automation for what happens after the conversation","CRM flow to capture the leads","Knowledge base written properly first"],
 faq=[("Will it make things up?","It is configured to refuse rather than guess, and tested against that. No system is perfect, which is why escalation is built in."),("Can we update it ourselves?","Yes. Updating the source documents updates the bot; the process is documented.")])

add(slug="crm", track="business", n="11", title="CRM &amp; customer flows",
 tag="Business · Operations",
 lead="Leads captured, tagged and followed up automatically, so nothing sits in an inbox for a week.",
 audience=["Companies losing enquiries between people","Sales teams whose pipeline lives in someone's head","Businesses that follow up when they remember"],
 problem="Most lost sales are not lost to a competitor. They are lost to a week of silence. The enquiry arrives, the person who could answer is busy, and by the time anyone returns to it the buyer has moved on.",
 solution="Every enquiry captured at the point of arrival, tagged, assigned and put on a follow-up schedule that does not depend on anyone remembering. Simple enough that your team uses it, because a CRM nobody updates is worse than none.",
 process=[("Pipeline","The stages you actually have, not the textbook ones."),("Capture","Every route in — form, email, phone, chat."),("Automation","Assignment, tagging, follow-up sequences."),("Migration","Existing contacts imported and de-duplicated."),("Training","For the people who will use it daily.")],
 delivers=["Configured CRM with your pipeline","All enquiry routes captured automatically","Follow-up sequences written and scheduled","Existing contacts migrated","Training session and written guide"],
 price="from kr 12 500", time="3–5 weeks",
 extras=["Reporting dashboard on the pipeline","Chatbot feeding the top of it","AI automation for quoting","Email marketing"],
 faq=[("Which CRM?","Usually one you already have or a light one you will not resent paying for. Chosen for your team size."),("Is this GDPR-compliant?","Configured to be: lawful basis recorded, retention set, deletion possible. The full standard is in our legal notice.")])

add(slug="process-automation", track="business", n="12", title="Business process automation",
 tag="Business · Operations",
 lead="Several connected tasks automated as one programme, not one script at a time.",
 audience=["Companies that have automated one thing and want the rest","Businesses whose systems do not talk to each other","Organisations scaling past what manual coordination survives"],
 problem="Point automations help and then stop helping, because the work does not live in one task. The order arrives in one system, the invoice in another, the project in a third, and a person spends their week carrying data between them.",
 solution="The chain mapped end to end and automated as one programme: systems connected, data flowing once, exceptions surfaced to a person rather than hidden. Delivered in stages so value arrives before the whole thing is finished.",
 process=[("End-to-end map","Every step, system and handover in the chain."),("Priority","Where the time and the errors actually are."),("Stage one","The highest-value link, built and proven."),("Connect","Systems integrated, data entered once."),("Exceptions","What the machine must escalate, and to whom."),("Documentation and training","")],
 delivers=["End-to-end process map","Staged automation, value at each stage","System integrations","Exception handling with named owners","Documentation and team training","Quarterly review for a year"],
 price="from kr 34 000", time="6–12 weeks, staged",
 extras=["Reporting dashboard across the whole chain","CRM as the spine","Chatbot at the customer end"],
 faq=[("Do we have to replace our systems?","Usually not. We connect what you have before suggesting you buy anything."),("What if a stage does not pay off?","Staged delivery exists so you can stop after any stage and keep what works.")])

add(slug="reporting", track="business", n="13", title="Reporting &amp; data analysis",
 tag="Business · Operations",
 lead="One dashboard that answers the three questions you actually ask every month.",
 audience=["Companies with data in five places and answers in none","Owners who reconstruct the same numbers monthly by hand","Boards asking for a figure nobody can produce quickly"],
 problem="Most companies have plenty of data and no answers, because the numbers live in separate systems and getting them into one place is a manual job somebody does badly once a month. So decisions get made on impressions.",
 solution="Three questions agreed first — the ones you genuinely ask — then a dashboard that answers exactly those, refreshed automatically. Not forty charts nobody reads. Definitions written down so the number means the same thing next quarter.",
 process=[("The three questions","Agreed and written before anything is built."),("Sources","Where each number actually comes from."),("Definitions","What counts as a sale, a lead, a customer — in writing."),("Build","Dashboard, refreshed automatically."),("Reading session","How to interpret it and what to do about it.")],
 delivers=["Dashboard answering the agreed questions","Automatic data refresh","Written metric definitions","Monthly summary in plain language","One reading and training session"],
 price="from kr 9 500", time="3–5 weeks",
 extras=["CRM as a clean data source","Process automation to fix the collection","SEO and campaign data included"],
 faq=[("Which tool?","Whatever your data and budget suit. Often something you already pay for."),("Can it include our accounting figures?","Yes, read-only, with access you control.")])

# ---------------- AI EMPLOYEES ----------------
# Three named roles that stay on duty when the office is closed. Sold as a
# setup fee plus a monthly fee, because they are staff, not a project.

add(slug="ai-receptionist", track="business", n="14", title="AI receptionist",
 tag="Business · AI employee",
 lead="Answers every call, message and booking request, at three in the morning as readily as at eleven.",
 audience=["Clinics, salons, workshops and trades who lose bookings to a ringing phone","Small teams where whoever is nearest answers, badly, mid-task","Anyone whose customers write at night and buy from whoever replies first"],
 problem="A missed call is rarely a customer who calls back. They call the next name on the list. Most small companies know this and still miss a third of their calls, because the person who could answer is holding a drill, a client, or a child. The usual fix is an answering service that reads a script and takes a message — which is a slower way of not answering.",
 solution="A receptionist that is on duty every hour of the year. It answers the phone and the message channels in your voice, knows your opening hours, prices and services, books straight into your calendar, and hands anything it cannot settle to a named person with the whole conversation attached. It never puts anyone on hold and never has a bad morning.",
 process=[("What it must know","Services, prices, hours, the ten questions you answer every week, and what it must never promise."),("Voice","How it greets people, how formal it is, and what it says when it does not know."),("Calendar and channels","Phone, web chat, SMS and email connected to the booking system you already use."),("Escalation","Which situations go to a person immediately, and to whom."),("Two weeks supervised","Every conversation reviewed by us and by you, and the answers corrected."),("Handover","Transcripts, monthly summary, and a way to change any answer yourself.")],
 delivers=["A receptionist answering phone, chat, SMS and email around the clock","Booking written directly into your calendar","Escalation rules with named owners","Full transcript of every conversation, kept under your control","Monthly summary: calls taken, bookings made, questions it could not answer","Two weeks of supervised operation before it runs on its own"],
 price="from kr 14 000 setup, then kr 2 900 / month", time="3–4 weeks to live",
 extras=["Norwegian and English on the same number","Chatbot on the website using the same knowledge","CRM so every conversation lands on a customer record"],
 faq=[("Will callers know it is not a person?","Yes — it says so in the greeting. Pretending otherwise is both wrong and, for calls, legally risky in several markets."),("What happens when it does not know?","It says so, takes the details, and passes the whole conversation to the person you named. It is not allowed to guess about prices or availability."),("Who owns the recordings and transcripts?","You do. Retention is set by you, deletion is possible on request, and the lawful basis is recorded — the detail is in our legal notice.")])

add(slug="ai-sales-assistant", track="business", n="15", title="AI sales assistant",
 tag="Business · AI employee",
 lead="Answers the buying questions the moment they are asked, qualifies the enquiry, and books the meeting.",
 audience=["Companies whose enquiries arrive outside office hours","Sales teams spending their day on enquiries that were never going to buy","Businesses with a long price list and a short attention span to explain it"],
 problem="Most enquiries are lost in the gap between interest and reply. Someone asks a question at nine in the evening, gets an answer at eleven the next morning, and has already bought elsewhere. The enquiries that do get answered quickly are often the ones that were never going to buy, so the fast reply is spent on the wrong person.",
 solution="An assistant that replies immediately, answers the product and price questions properly, works out whether this is a real opportunity by asking the four questions your sales process actually depends on, and books qualified people into a calendar. Unqualified enquiries get an honest, useful answer rather than a chase.",
 process=[("Your offer, written down","Products, prices, what you do not sell, and what you will not discount."),("Qualification","The four questions that decide whether an enquiry is worth a meeting."),("Objections","The six you hear most, and the answer you want given."),("Handover point","Exactly where a person takes over, and what they receive."),("Two weeks supervised","Real enquiries, reviewed daily, answers corrected."),("Reporting","What came in, what qualified, what was booked, what was lost and why.")],
 delivers=["Immediate reply on web chat, email and the messaging channels you use","Qualification against your own criteria, not a generic template","Meetings booked into the calendar of the right person","A written record of every enquiry with the reason it did or did not qualify","Monthly report: enquiries, qualification rate, meetings, common objections","Two weeks of supervised operation before it runs on its own"],
 price="from kr 19 000 setup, then kr 3 900 / month", time="4–5 weeks to live",
 extras=["CRM so the pipeline is visible without a spreadsheet","Landing page built around the questions it hears most","Reporting dashboard combining sales and marketing data"],
 faq=[("Will it discount to close a deal?","No. It quotes your published prices and has no authority to go below them. Discounts are a human decision."),("What if it gives a wrong answer about a product?","It answers only from the material you approved, and says it will check when asked something outside it. The two supervised weeks exist to find the gaps before customers do."),("Does it replace a salesperson?","It replaces the first hour of their day. The meeting, the negotiation and the relationship stay human.")])

add(slug="ai-office-assistant", track="business", n="16", title="AI office assistant",
 tag="Business · AI employee",
 lead="Sorts the inbox, drafts the routine documents, chases the things everyone forgets.",
 audience=["Owners doing three hours of administration after the working day ends","Offices where one person is the bottleneck for every document","Teams whose systems each need the same information typed in again"],
 problem="Administration is not difficult; it is relentless. Sorting an inbox, drafting the same three letters, entering an order into two systems, remembering that an invoice is nine days overdue. None of it needs judgement, all of it needs doing, and it is almost always done by the person whose time is worth the most.",
 solution="An assistant that takes the routine layer: the inbox triaged by what needs a decision and what does not, the standard documents drafted from your own templates, data entered once and carried across, and the quiet chases sent on time. Everything it produces is a draft until a person approves it, so nothing leaves the building unread.",
 process=[("Time audit","Two weeks of what actually consumes the administrative day."),("The routine list","Which tasks are rule-based, which need judgement, and which must never be automated."),("Templates","Your documents, your wording, your signature blocks."),("Approval gates","What it may send on its own, and what waits for a person."),("Build and connect","Inbox, calendar, storage and accounting connected."),("Supervised fortnight, then documentation and training","")],
 delivers=["Inbox triaged daily into decide / read / no action","Routine documents drafted from your templates, ready to approve","Data entered once and carried into every connected system","Follow-ups and reminders sent on your schedule","A named list of what it may do alone and what it may not","Monthly summary of hours returned to you"],
 price="from kr 16 000 setup, then kr 3 400 / month", time="3–5 weeks to live",
 extras=["Business process automation for the chains it cannot cover alone","Reporting so the returned hours are measurable","CRM as the single place customer information lives"],
 faq=[("Can it send email as me?","Only what you put on the approved list. Everything else waits as a draft."),("What about confidential documents?","You name the folders and categories it may never touch, and it cannot reach them. Access is scoped, logged and revocable."),("How do we know it is saving time?","The time audit at the start gives the baseline, and the monthly summary reports against it. If the hours do not appear, the answer is to stop, not to add more automation.")])
