#!/usr/bin/env python3
"""Write the /on-brand skill's token reference, read off the stylesheets.

The rules of the brand are prose and they are stable, so `SKILL.md` is written
by hand. The *values* are not stable — a token can be renamed or retuned — and a
skill that quotes `#8B1A1A` from memory is a second copy of the truth that goes
wrong silently. That is the failure this repository has logged more times than
any other.

So the reference table is generated from the four stylesheets that actually
define the tokens, and from `brand/README.md` for the mark. Re-run after
touching any `:root`.

    python3 tools/generators/build_on_brand.py
"""

import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, ".claude", "skills", "on-brand", "references", "tokens.md")

# Where each property keeps its :root. The hub has no stylesheet — its CSS is
# one inline <style> block, which is itself a brand fact worth stating.
SHEETS = [
    ("The hub", "index.html", "inline <style> block"),
    ("Beta Art — the archive", "beta-art/styles.css", None),
    ("Beta Art Business — the desk", "beta-art-business/styles.css", None),
    ("Field Notes — the journal", "beta-art-blog/styles.css", None),
]

ROOT_BLOCK = re.compile(r":root\s*\{(.*?)\n\}", re.S)
DECL = re.compile(r"(--[a-z0-9-]+)\s*:\s*([^;]+);")


def tokens(rel):
    src = open(os.path.join(ROOT, rel), encoding="utf-8").read()
    m = ROOT_BLOCK.search(src)
    if not m:
        return {}
    return {k: " ".join(v.split()) for k, v in DECL.findall(m.group(1))}


def readme():
    return open(os.path.join(ROOT, "brand", "README.md"), encoding="utf-8").read()


def contrast(a, b):
    def lum(h):
        h = h.lstrip("#")
        out = []
        for i in (0, 2, 4):
            v = int(h[i:i + 2], 16) / 255
            out.append(v / 12.92 if v <= 0.03928 else ((v + 0.055) / 1.055) ** 2.4)
        return .2126 * out[0] + .7152 * out[1] + .0722 * out[2]
    l1, l2 = lum(a), lum(b)
    return (max(l1, l2) + .05) / (min(l1, l2) + .05)


def group(name):
    """Which table a token belongs in. Names, not values — the names are the
    vocabulary the skill enforces."""
    if name.startswith("--f-"):
        return "type"
    if name.startswith("--space-"):
        return "space"
    if name.startswith("--mono-"):
        return "type-size"
    if name in ("--wrap", "--measure"):
        return "measure"
    if name in ("--ease", "--dur"):
        return "motion"
    return "colour"


def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    sheets = [(label, rel, note, tokens(rel)) for label, rel, note in SHEETS]

    w = []
    a = w.append
    a("# Token reference\n")
    a("<!-- generated by tools/generators/build_on_brand.py — do not edit by hand -->\n")
    a("Read off the stylesheets, not written down. If a value here disagrees with")
    a("the site, the site is right and this file is stale: re-run the builder.\n")
    a("    python3 tools/generators/build_on_brand.py\n")
    a("**Use the token, never the value.** A hex code typed into a rule is invisible")
    a("to `tokens.py`, survives a palette change, and is the thing to refuse.\n")

    for label, rel, note, tk in sheets:
        a("## %s\n" % label)
        a("`%s`%s\n" % (rel, " — %s" % note if note else ""))
        if not tk:
            a("_No `:root` block found._\n")
            continue
        for key, title in [("colour", "Colour"), ("type", "Typeface"),
                           ("type-size", "Small type"), ("space", "Spacing"),
                           ("measure", "Measure"), ("motion", "Motion")]:
            rows = [(n, v) for n, v in tk.items() if group(n) == key]
            if not rows:
                continue
            a("**%s**\n" % title)
            a("| Token | Value |")
            a("|---|---|")
            for n, v in rows:
                a("| `%s` | `%s` |" % (n, v))
            a("")

    # The one cross-property fact that is a rule rather than a value.
    dark = dict(sheets[2][3])
    light = dict(sheets[1][3])
    a("## The two grounds\n")
    a("The archive and the journal are set on paper; the desk is set on ink. That")
    a("is why the desk's palette is a different set of names, not a dark variant of")
    a("the same ones — there is no `--paper` on the desk and no `--void` on the")
    a("archive. Do not carry a token across.\n")
    a("| | Light properties | The desk |")
    a("|---|---|---|")
    a("| Ground | `--paper` `%s` | `--void` `%s` |" % (light.get("--paper", "?"), dark.get("--void", "?")))
    a("| Text | `--ink` `%s` | `--text` `%s` |" % (light.get("--ink", "?"), dark.get("--text", "?")))
    a("| Accent | `--seal` `%s` | `--seal` `%s` |" % (light.get("--seal", "?"), dark.get("--seal", "?")))
    a("")
    a("`--seal` is the same red on both, and on ink it does not hold on its own —")
    a("that is what `--seal-bright` `%s` is for, and it exists **on dark grounds**"
      % dark.get("--seal-bright", "?"))
    a("only. It is not a second brand colour.\n")

    # One name, two values, two artefacts. Reported rather than resolved: which
    # red the mark's centre should be is a brand decision, not a build one.
    css = dark.get("--seal-bright", "")
    doc = re.search(r"seal-bright\s*\|\s*`(#[0-9A-Fa-f]{6})`", readme())
    if doc and css and doc.group(1).upper() != css.upper():
        a("### ⚠ `seal-bright` names two different colours\n")
        a("| Where | Value | On `%s` | Good for |" % dark.get("--void", "#0F0F0F"))
        a("|---|---|---|---|")
        for where, val in [("`beta-art-business/styles.css`", css),
                           ("`brand/README.md` (the mark's centre)", doc.group(1))]:
            r = contrast(val, dark.get("--void", "#0F0F0F"))
            level = ("body text and graphics" if r >= 4.5 else
                     "large text and graphics only" if r >= 3 else "nothing")
            a("| %s | `%s` | %.2f:1 | %s |" % (where, val, r, level))
        a("")
        a("The CSS value is on roughly fifty declarations, most of them 12–13px mono")
        a("— prices, kickers, accession numbers — so it has to clear 4.5:1 and does.")
        a("The mark's centre is a graphic element and 3:1 is enough for it. Both may")
        a("be correct; **the name is not**, because one token name pointing at two")
        a("values is how a palette change goes half-applied. Naming them apart is a")
        a("person's call, so this reports and does not choose.\n")

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(w))

    total = sum(len(t) for _, _, _, t in sheets)
    print(".claude/skills/on-brand/references/tokens.md — %d tokens from %d files"
          % (total, len([s for s in sheets if s[3]])))


if __name__ == "__main__":
    main()
