CATS = [("ai","AI"),("business","Work life"),("job-search","Job search"),("career","Career"),
        ("marketing","Digital marketing"),("web","Web design"),("startup","Entrepreneurship"),
        ("automation","Automation"),("income","Side income"),("small-business","Small business")]

P = []
def add(**k): P.append(k)

add(slug="website-cost", cat="web", cat2="small-business", date="2026-08-12", read="7 min",
 short="What a website actually costs in Norway",
 title="What a website actually costs in Norway, and why nobody will tell you",
 lead="Three quotes for the same brief came back at kr 18 000, kr 140 000 and “let’s have a meeting”. All three were honest. Here is what moves the number.",
 body=[
 ("h2","The number depends on four things, and only four"),
 ("p","Every quote you receive is a function of scope, content, integrations and who maintains it afterwards. Agencies rarely say this out loud, because saying it invites you to reduce the scope — which reduces the invoice."),
 ("p","<strong>Scope.</strong> A one-page site and a forty-page site are not the same product. If you sell one thing, one page will out-perform five, and it costs a fifth as much. Most companies buy pages they will never update because the sitemap was drawn before anyone asked what each page was for."),
 ("p","<strong>Content.</strong> Who writes it? This is the single biggest hidden cost. A build quoted at kr 24 000 assumes the text exists. It usually does not, and the project then stalls for two months while somebody who is not a writer tries to write. Writing the content is real work and should be a line on the quote, not an assumption."),
 ("p","<strong>Integrations.</strong> Booking, payment, CRM, inventory, a login. Each one is a system that can break independently and needs testing against real data. Two integrations can cost more than the entire front end."),
 ("p","<strong>Maintenance.</strong> Who edits it in March? If the answer is “the agency”, you are buying a subscription, not a website. That is a legitimate choice — but it should be priced and named, not discovered later."),
 ("h2","Realistic ranges, in NOK excluding VAT"),
 ("ul",["<strong>kr 9 000 – 15 000</strong> — one page, your content, no integrations. A campaign page or a personal site.",
        "<strong>kr 24 000 – 40 000</strong> — a real company site, five to twelve pages, content written for you, no complex integrations.",
        "<strong>kr 40 000 – 90 000</strong> — the above plus e-commerce or two or three integrations, or several languages.",
        "<strong>Above kr 100 000</strong> — custom systems, many languages, or a team of five people, which is a different kind of supplier from us."]),
 ("h2","Why the cheap quote is sometimes right"),
 ("p","A kr 18 000 quote is not automatically a warning sign. It is the correct price for a small scope done by someone efficient. It becomes a problem when it is the correct price for a small scope and you were describing a large one — and neither party noticed, because nobody wrote the scope down."),
 ("p","That is the actual test. Not the number: whether the quote comes with a written scope you can hold it to. A cheap quote with a precise scope is safe. An expensive quote with a vague one is not."),
 ("h2","The four questions to ask every supplier"),
 ("ol",["Who writes the content, and is it in this price?",
        "What happens if we are late — for you, and for us?",
        "Who owns the source files, the domain and the hosting account after launch?",
        "What does a small change cost in six months, and who does it?"]),
 ("p","Any supplier who answers those four clearly is worth talking to at any price. Any supplier who deflects them is expensive at every price."),
 ],
 cta=("website","Website"))

add(slug="cv-ats", cat="job-search", cat2="career", date="2026-08-05", read="6 min",
 title="The CV format that clears applicant-tracking systems",
 lead="Sixty applications and four replies is usually not a talent problem. It is a parsing problem, and it is fixable in an afternoon.",
 body=[
 ("h2","What actually happens to your file"),
 ("p","Before a person sees your CV, software reads it. It extracts text, looks for the terms in the advert, and ranks the result. It reads top to bottom, left to right, and it does not understand design."),
 ("p","Which means a two-column layout with your job titles in a sidebar can parse as an empty document. The information is on the page; it is not in the file in an order the parser can follow. The candidate never knows, because the rejection is silent."),
 ("h2","The rules that matter"),
 ("ul",["<strong>One column.</strong> Sidebars, text boxes and tables are where information goes to disappear.",
        "<strong>Real headings.</strong> The words Experience, Education, Skills — not clever alternatives. The parser is looking for the boring words.",
        "<strong>Dates in one format,</strong> on the same line as the role. Month Year – Month Year.",
        "<strong>No text inside images.</strong> A logo is fine. Your name as a graphic is not.",
        "<strong>.docx or a text-based PDF.</strong> A PDF exported from a design tool is often one flat image with no text at all.",
        "<strong>File name:</strong> firstname-lastname-cv.pdf. It is the first thing a human reads."]),
 ("h2","What to write, once it can be read"),
 ("p","Lead with the result, not the responsibility. “Responsible for social media” tells a reader nothing. “Grew the account from 400 to 6 000 followers in nine months, and the enquiries that came with it” tells them what happens if they hire you."),
 ("p","Put a number in at least half your lines. If you have no numbers, use scale: how many people, how many customers, how big a budget. Never invent one — you will be asked about it in the interview, and that is a worse outcome than a vague line."),
 ("h2","Tailoring without rewriting"),
 ("p","You do not need a new CV per application. You need three variable lines: the summary sentence, the top three skills, and the first bullet of your most recent role. Change those three to echo the advert’s own words. Leave everything else alone."),
 ("p","That takes four minutes per application instead of forty, which matters, because volume is part of the job search whether anyone admits it or not."),
 ("h2","The uncomfortable part"),
 ("p","None of this makes a weak application strong. It makes a strong application readable. If you rebuild the format and still get no replies after twenty applications, the problem is upstream — the roles, the market, or the story you are telling about the change you are making. That is a different conversation, and it is worth having honestly rather than sending the twenty-first."),
 ],
 cta=("cv","CV &amp; job applications"))

add(slug="what-to-automate", cat="automation", cat2="small-business", date="2026-07-29", read="6 min",
 title="Which tasks are worth automating, and which are not",
 lead="Most automation projects fail on the choice of task, not on the technology. There is a simple test.",
 body=[
 ("h2","The test"),
 ("p","A task is worth automating when it is <strong>frequent</strong>, <strong>rule-based</strong> and <strong>low-judgement</strong>. All three. Miss one and you will spend more on the automation than the task ever cost you."),
 ("p","Frequent means several times a week, not several times a year. Rule-based means you can write down what happens without using the word “depends”. Low-judgement means being wrong is cheap and visible, not expensive and silent."),
 ("h2","Good candidates"),
 ("ul",["Retyping enquiry details from an email into a system.",
        "Sending the same follow-up three days after a quote.",
        "Renaming and filing attachments by a rule.",
        "Producing the same monthly report from the same three sources.",
        "Answering the twenty questions your inbox gets every week."]),
 ("h2","Bad candidates, however tempting"),
 ("ul",["<strong>Pricing anything unusual.</strong> The exception is where the money is, and the machine has never seen it.",
        "<strong>Anything a customer will read as a person’s voice.</strong> Automate the draft, not the send.",
        "<strong>A task done twice a month.</strong> Twenty-four times a year does not repay three weeks of work.",
        "<strong>A process nobody has written down.</strong> Automating an undocumented process encodes the confusion."]),
 ("h2","Start with the one you hate"),
 ("p","Given two candidates of equal value, automate the one that annoys you most. Not because irritation is a good metric, but because the automation you resent doing the setup for is the one that never gets adopted. One working automation earns more trust — and more of the next budget — than a platform nobody logs into."),
 ("h2","Keep a person in the loop where it matters"),
 ("p","The most common mistake after choosing well is removing the human check to save two more minutes. A quote that goes out wrong costs more than every minute the automation saved. Draft automatically, approve manually, send automatically. The approval step is the product, not the friction."),
 ("h2","Document it or lose it"),
 ("p","The person who requested the automation will eventually leave, change role, or forget. If the workflow is not written down — what it does, what it assumes, what to do when it fails — it becomes a black box everyone is afraid to touch, and in eighteen months somebody quietly goes back to doing it by hand."),
 ],
 cta=("ai-automation","AI automation"))

add(slug="ai-small-business", cat="ai", cat2="small-business", date="2026-07-22", read="7 min",
 title="AI in a small business: what works, what wastes money",
 lead="After a year of building these for other people, a short and unglamorous list.",
 body=[
 ("h2","What reliably works"),
 ("ul",["<strong>First drafts.</strong> Of anything you would otherwise stare at: quotes, replies, product descriptions, job adverts. The edit is faster than the blank page.",
        "<strong>Sorting and extracting.</strong> Pulling structured fields out of unstructured email. Deeply boring, immediately valuable.",
        "<strong>Answering from your own documents.</strong> A support assistant that quotes your own manual is useful. One that improvises is a liability.",
        "<strong>Research summaries</strong> where you will check the sources anyway."]),
 ("h2","What wastes money"),
 ("ul",["<strong>Buying a tool before naming a task.</strong> The licence is the cheap part; the setup nobody did is the expensive part.",
        "<strong>Publishing unedited output.</strong> It is recognisable, and it costs you the credibility the content was meant to build.",
        "<strong>Chatbots with no escalation.</strong> A bot that cannot say “I will get a person” is worse than no bot.",
        "<strong>Replacing judgement.</strong> Pricing, hiring, anything legal. The confident wrong answer is the dangerous one."]),
 ("h2","The question to ask a supplier"),
 ("p","Ask what happens to your data. Specifically: does the material we send train a model, and which service is it going to? If the answer is vague, that is the answer. The right answer names the service and says training-excluded or enterprise mode, in writing."),
 ("p","Ask the second question too: which parts of what you deliver are machine-assisted? A supplier who will not answer that is charging you for judgement they are not applying."),
 ("h2","A realistic first year"),
 ("p","Automate one task. Live with it for a month. Then automate the next. Companies that buy a platform and try to move everything at once usually end up back where they started, plus a subscription."),
 ("p","The businesses getting real value from this are not doing anything exotic. They picked the dullest repeated task in the week, handed it over properly, wrote down how it works, and moved on to the next one. That is the whole method."),
 ],
 cta=("ai-automation","AI automation"))

add(slug="pricing-first-project", cat="income", cat2="startup", date="2026-07-15", read="6 min",
 title="How to price your first freelance project",
 lead="The number you are afraid to say out loud is usually the right one. Here is how to get to it without guessing.",
 body=[
 ("h2","Start from the year, not the hour"),
 ("p","Decide what you need to earn in a year. Divide by the weeks you will actually work — 44, not 52. Divide by the hours you can actually bill — 20 a week, not 40, because selling, admin and accounting are unpaid. The number that falls out is your floor."),
 ("p","Most people are shocked by it, and then quote below it anyway. The shock is the useful part: it tells you that the hourly rate you had in mind was a salary rate, and a salary comes with holiday pay, sick pay and a pension you now have to fund yourself."),
 ("h2","Then stop selling hours"),
 ("p","Use the hourly figure to sanity-check a fixed price, never to quote one. Hourly billing punishes you for getting faster and makes the client watch the clock instead of the outcome. Quote the job."),
 ("p","To quote a job: estimate the hours honestly, add 30% for the revisions you have not imagined yet, multiply by your rate, and round up. The 30% is not padding. It is the part of every project that nobody scopes and everybody does."),
 ("h2","Say the number and stop talking"),
 ("p","The silence after a price is the hardest four seconds in freelancing, and filling it is the most expensive habit in the trade. Most discounts are given to a silence, not to a negotiation."),
 ("h2","When they say it is too expensive"),
 ("p","Do not reduce the price. Reduce the scope, and say what is coming out. “I can do it for that — it would be the one page rather than the five.” This keeps your rate intact, teaches the client that price tracks scope, and often ends with them finding the original budget."),
 ("h2","Raise it earlier than feels comfortable"),
 ("p","Raise on new clients first; existing ones keep the old rate for a stated period. If nobody has said no in six months, you are too cheap. A small number of refusals is evidence of correct pricing, not of failure."),
 ],
 cta=("portfolio","Portfolio"))

add(slug="seo-without-marketing", cat="marketing", cat2="small-business", date="2026-07-08", read="7 min",
 title="SEO for a company with no marketing department",
 lead="Four things, in order. Do them and you will beat most of your competitors, who have not.",
 body=[
 ("h2","One: fix what is broken before writing anything"),
 ("p","Content on a broken site is money set on fire. Check four things: every page has one h1 that describes it, every page has a unique title under sixty characters, the site loads in under two and a half seconds on a phone, and Search Console is verified so you can see what is happening."),
 ("p","That is usually a day of work, and it is the highest-return day you will spend."),
 ("h2","Two: one page per thing you sell"),
 ("p","The single most common structural mistake is a services page listing eight services. It ranks for none of them, because it is specifically about nothing. Eight pages, each about one service, each answering that service’s own question, will each rank for their own term."),
 ("p","This is also why every service on this site has its own page. It is not a design preference; it is the structure search rewards, and it happens to be the structure buyers prefer too."),
 ("h2","Three: answer the questions you already get asked"),
 ("p","Your salespeople answer the same questions every week. Those are the questions people type into search. Write the answers down, publicly, once each. You do not need a content strategy for this — you need a list of the last twenty questions a customer asked, and the discipline to answer one a week."),
 ("h2","Four: measure three things, not thirty"),
 ("p","Organic sessions, enquiries from organic, and which pages produce them. Everything else is decoration until those three are moving."),
 ("h2","What to ignore"),
 ("ul",["<strong>Keyword density.</strong> Not a thing for roughly a decade.",
        "<strong>Buying links.</strong> A risk you cannot unwind.",
        "<strong>Anyone guaranteeing position one.</strong> Nobody can. The guarantee is the tell.",
        "<strong>Blogging weekly about nothing.</strong> Twelve pieces that answer real questions beat fifty that answer none."]),
 ("h2","How long it takes"),
 ("p","Technical fixes show within weeks. Structure shows in one to three months. Content ranks in three to six. Anyone promising faster is describing paid advertising, which is a fine thing to buy — but it stops the day you stop paying, and this does not."),
 ],
 cta=("seo","SEO"))

add(slug="einvoicing-2027", cat="small-business", cat2="automation", date="2026-08-18", read="6 min",
 short="Mandatory e-invoicing in Norway from 2027",
 title="Every Norwegian business must issue e-invoices from 1 January 2027",
 lead="The date moved forward a year and most small companies have not heard. Here is what actually changes, and what to do about it in 2026 rather than in December.",
 body=[
 ("h2","What was decided"),
 ("p","The Ministry of Finance has brought mandatory business-to-business e-invoicing forward by a year, from 1 January 2028 to <strong>1 January 2027</strong>. From that date every business subject to Norwegian bookkeeping obligations must <em>issue</em> invoices in a structured electronic format \u2014 not a PDF, not a scan, not an attachment."),
 ("p","A second stage follows on <strong>1 January 2030</strong>: mandatory digital bookkeeping, and a mandatory ability to <em>receive</em> e-invoices. Businesses under kr 50 000 in turnover are proposed to be exempt. The detailed technical rules are expected during 2026."),
 ("h2","What counts as an e-invoice"),
 ("p","Not a PDF. This is the single most common misunderstanding, and it will cost people time in December 2026. A PDF is a picture of an invoice; the requirement is for structured data a machine can read without guessing \u2014 in practice EHF, Norway\u2019s Peppol-based national format, already mandatory for anyone selling to the state, counties or municipalities."),
 ("p","If you already invoice a kommune, you are already doing this. If you have never sold to the public sector, you probably are not."),
 ("h2","Who this affects most"),
 ("ul",["<strong>Sole proprietorships above kr 50 000</strong> who invoice from a spreadsheet or a Word template. This is the group with the most work to do and the least warning.",
        "<strong>Small companies on an old accounting package</strong> that exports PDF only. Check whether your version supports EHF, not whether the vendor\u2019s website mentions it.",
        "<strong>Anyone invoicing through a webshop or booking system</strong> that generates its own documents. That system now has a compliance requirement attached to it."]),
 ("h2","What to do in 2026, in order"),
 ("ol",["<strong>Find out what your current system can do.</strong> One question to your accounting provider: does this issue EHF 3.0 over Peppol, on my plan? Get the answer in writing.",
        "<strong>If the answer is no, change provider this year, not next.</strong> Migrating an accounting system in the same quarter as the deadline is how people end up invoicing late.",
        "<strong>Get a Peppol address.</strong> Your provider usually registers it for you; it takes days, not months.",
        "<strong>Send one real invoice through it</strong> to a customer who can confirm receipt. A test invoice that nobody opens proves nothing.",
        "<strong>Check your customer data.</strong> Organisation numbers must be correct and present. This is the boring failure that stops delivery, and it is easier to fix now than at volume."]),
 ("h2","The part worth saying plainly"),
 ("p","This is not a reason to buy anything from us. For most small companies it is a conversation with the accounting provider you already pay, and it ends there. If your invoicing runs through a system somebody built for you \u2014 a shop, a booking flow, a custom back office \u2014 then it is a development task, and that is where we would be useful."),
 ("p","Either way, the mistake is treating a 1 January date as a January problem. The systems people are queuing for in December will be the same systems, with a queue."),
 ],
 cta=("process-automation","Business process automation"))
